export const BRAND_PAGES = [
  { slug: 'dri-duck', name: 'DRI DUCK', tagline: 'Built for work, weather, and everyday wear.', description: 'Outdoor-ready blanks, jackets, fleece, headwear, and workwear options for teams, brands, and businesses.', categories: ['fleece', 'outerwear', 'hats', 'womens'], logo: '/brands/dri-duck.jpg' },
  { slug: 'comfort-colors', name: 'Comfort Colors', tagline: 'Garment-dyed blanks with a soft, lived-in feel.', description: 'Tees, long sleeves, sweatshirts, and casual blanks for brands, creators, events, and everyday apparel.', categories: ['t_shirts', 'long_sleeve', 'crewnecks', 'hoodies', 'tank_tops', 'kids'], logo: '/brands/comfort-colors.jpg' },
  { slug: 'gildan', name: 'Gildan', tagline: 'Everyday blanks for every kind of project.', description: 'Reliable tees, fleece, and more for brands, teams, events, and bulk orders.', categories: ['t_shirts', 'hoodies', 'fleece', 'crewnecks'], logo: '/brands/gildan.jpg' },
  { slug: 'shaka-wear', name: 'Shaka Wear', tagline: 'Streetwear-ready blank essentials.', description: 'Structured tees and versatile blanks for creators, brands, and teams.', categories: ['t_shirts', 'long_sleeve', 'hoodies'], logo: '/brands/shaka-wear.jpg' },
  { slug: 'champion', name: 'Champion', tagline: 'Champion blanks for teams, businesses, organizations, and everyday wear.', description: 'Explore sports, teamwear, staff apparel, corporate-casual layers, and premium everyday Champion blanks through HC Apparel.', categories: ['sportswear', 'business_apparel', 'polos', 'quarter_zips', 'outerwear', 'hoodies', 'crewnecks', 'womens', 'mens'], logo: '/brands/champion.jpg' },
  { slug: 'columbia', name: 'Columbia', tagline: 'Ready for colder days and outdoor work.', description: 'Explore fleece, outerwear, and everyday gear for teams and businesses.', categories: ['outerwear', 'fleece', 'sportswear'], logo: '/brands/columbia.jpg' },
  { slug: 'bella-canvas', name: 'Bella + Canvas', tagline: 'Versatile blanks for creative projects.', description: 'Shop tees and other apparel blanks for brands, creators, and events.', categories: ['t_shirts', 'tank_tops', 'womens'], logo: '/brands/bella-canvas.jpg' },
  { slug: 'next-level', name: 'Next Level', tagline: 'Modern blanks for your next idea.', description: 'Explore tees and everyday apparel for teams, businesses, and creators.', categories: ['t_shirts', 'tank_tops', 'womens'], logo: '/brands/next-level.jpg' },
  { slug: 'hanes', name: 'Hanes', tagline: 'Dependable everyday apparel blanks.', description: 'Find approachable tees, fleece, and basics for groups and bulk orders.', categories: ['t_shirts', 'hoodies', 'fleece', 'kids'], logo: '/brands/hanes.jpg' },
  { slug: 'rabbit-skins', name: 'Rabbit Skins', tagline: 'Little sizes for big ideas.', description: 'Explore youth and family-friendly apparel blanks for schools, events, creators, and teams.', categories: ['kids', 't_shirts', 'hoodies'], logo: '/brands/rabbit-skins.jpg' },
  { slug: 'port-company', name: 'Port & Company', tagline: 'Practical blanks for groups and teams.', description: 'Browse apparel options for uniforms, events, schools, and businesses.', categories: ['t_shirts', 'hoodies', 'polos', 'hats'] },
  { slug: 'independent-trading-co', name: 'Independent Trading Co.', tagline: 'Fleece and layers made for the everyday.', description: 'Shop hoodie, sweatshirt, and outerwear blanks for brands and teams.', categories: ['hoodies', 'fleece', 'crewnecks', 'outerwear'] },
  { slug: 'adidas', name: 'adidas', tagline: 'Sport-minded apparel for active teams.', description: 'Explore activewear and versatile apparel blanks for groups and organizations.', categories: ['sportswear', 'polos', 'outerwear'] },
  { slug: 'oakley', name: 'Oakley', tagline: 'Performance-inspired everyday gear.', description: 'Shop apparel and accessories for active teams and businesses.', categories: ['sportswear', 'polos', 'hats', 'bags'], logo: undefined },
];

export const brandPageBySlug = slug => BRAND_PAGES.find(brand => brand.slug === slug);
export const brandPageByName = name => BRAND_PAGES.find(brand => brand.name.toLowerCase().replace(/[^a-z0-9]/g, '') === String(name || '').toLowerCase().replace(/[^a-z0-9]/g, ''));
