import React, { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, Truck } from 'lucide-react';
import { Link } from 'react-router-dom';
import { toast } from 'sonner';
import { base44 } from '@/api/base44Client';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';

const initial = { id:'default', minimum_margin_per_item:3, processing_enabled:true, processing_percent:3.5, processing_fixed_fee:.5, sales_tax_enabled:false, sales_tax_rate_percent:0, ss_shipping_enabled:true, ss_free_freight_threshold:200, ss_tier_1_2:'', ss_tier_3_5:'', ss_tier_6_12:'', ss_tier_13_plus:'', ss_shipping_buffer:0, usps_enabled:false, usps_ground_advantage_enabled:true, usps_priority_mail_enabled:true, origin_street:'', origin_city:'', origin_state:'', origin_zip:'', default_product_weight_oz:'', default_product_weight_unit:'oz', default_package_length_in:'', default_package_width_in:'', default_package_height_in:'', default_package_dimension_unit:'in', hc_fallback_enabled:false, hc_fallback_rate:'', hc_free_shipping_enabled:false, hc_free_shipping_threshold:'', hc_handling_amount:0 };
const numbers = new Set(['minimum_margin_per_item','processing_percent','processing_fixed_fee','sales_tax_rate_percent','ss_free_freight_threshold','ss_tier_1_2','ss_tier_3_5','ss_tier_6_12','ss_tier_13_plus','ss_shipping_buffer','default_product_weight_oz','default_package_length_in','default_package_width_in','default_package_height_in','hc_fallback_rate','hc_free_shipping_threshold','hc_handling_amount']);
const testInitial = { destination_zip:'', weight:'', weight_unit:'oz', length:'', width:'', height:'', dimension_unit:'in' };
const weightUnits=[{value:'oz',label:'Ounces (oz)'},{value:'lb',label:'Pounds (lb)'}];
const dimensionUnits=[{value:'in',label:'Inches (in)'},{value:'cm',label:'Centimeters (cm)'}];
function Field({ label, name, form, setForm, note }) { return <label className="block text-sm font-medium">{label}<Input className="mt-1" type={numbers.has(name)?'number':'text'} step={numbers.has(name)?'0.01':undefined} min={numbers.has(name)?'0':undefined} value={form[name]??''} onChange={e=>setForm(v=>({...v,[name]:e.target.value}))}/>{note&&<span className="mt-1 block text-xs font-normal text-muted-foreground">{note}</span>}</label>; }
function NumberField({ label, name, form, setForm }) { return <label className="block text-sm font-medium">{label}<Input className="mt-1" type="number" min="0.01" step="0.01" value={form[name]} onChange={e=>setForm(v=>({...v,[name]:e.target.value}))}/></label>; }
function Toggle({ label, name, form, setForm }) { return <label className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" checked={Boolean(form[name])} onChange={e=>setForm(v=>({...v,[name]:e.target.checked}))}/>{label}</label>; }
function Unit({ label, name, form, setForm, options }) { return <label className="block text-sm font-medium">{label}<select className="mt-1 h-10 w-full rounded-md border bg-background px-3 text-sm" value={form[name]} onChange={e=>setForm(v=>({...v,[name]:e.target.value}))}>{options.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label>; }

export default function AdminPaymentFeeSettings() {
  const queryClient=useQueryClient();
  const [form,setForm]=useState(initial);
  const [test,setTest]=useState(testInitial);
  const [uspsResult,setUspsResult]=useState(null);
  const {data=[],isLoading}=useQuery({queryKey:['checkout-financial-settings'],queryFn:()=>base44.entities.CheckoutFinancialSettings.list()});
  const record=data[0];
  useEffect(()=>{if(record)setForm({...initial,...record});},[record]);
  const save=useMutation({mutationFn:async()=>{const payload=Object.fromEntries(Object.entries(form).filter(([k])=>!['id','updated_at','updated_by','origin_name'].includes(k)).map(([k,v])=>[k,numbers.has(k)?(v===''?null:Number(v)):v])); return record?base44.entities.CheckoutFinancialSettings.update(record.id,payload):base44.entities.CheckoutFinancialSettings.create({id:'default',...payload});},onSuccess:()=>{queryClient.invalidateQueries({queryKey:['checkout-financial-settings']});toast.success('Pricing and shipping settings saved.');},onError:e=>toast.error(e.message)});
  const testUsps=useMutation({mutationFn:()=>base44.functions.invoke('checkout-pricing',{action:'usps_rate_test',payload:{origin_zip:form.origin_zip,destination_zip:test.destination_zip,weight:test.weight,weight_unit:test.weight_unit,length:test.length,width:test.width,height:test.height,dimension_unit:test.dimension_unit,ground_enabled:form.usps_ground_advantage_enabled,priority_enabled:form.usps_priority_mail_enabled,fallback_enabled:form.hc_fallback_enabled,fallback_amount:form.hc_fallback_rate}}),onSuccess:result=>{setUspsResult(result.data);toast.success('USPS rate test completed.');},onError:error=>{setUspsResult({error:error.message});toast.error(error.message);}});
  return <div className="min-h-screen bg-muted/30"><header className="bg-primary px-4 py-6 text-primary-foreground"><div className="container mx-auto max-w-5xl"><Link to="/AdminDashboard"><Button size="sm" variant="ghost" className="-ml-3 text-primary-foreground"><ArrowLeft className="mr-1 h-4 w-4"/>Admin Dashboard</Button></Link><h1 className="mt-2 flex items-center gap-2 text-2xl font-extrabold"><Truck className="text-accent"/>Pricing & Shipping Settings</h1><p className="mt-1 text-sm text-primary-foreground/70">Server-side checkout rules. Carrier and vendor credentials are never shown here.</p></div></header>
    <main className="container mx-auto max-w-5xl space-y-6 px-4 py-8">{isLoading?<div>Loading settings…</div>:<form className="space-y-6" onSubmit={e=>{e.preventDefault();save.mutate();}}>
      <Card className="space-y-4 p-6"><h2 className="text-lg font-bold">Pricing rules & payment processing</h2><div className="grid gap-4 md:grid-cols-3"><Field label="Minimum margin per item ($)" name="minimum_margin_per_item" form={form} setForm={setForm}/><Field label="Processing percentage (%)" name="processing_percent" form={form} setForm={setForm}/><Field label="Fixed transaction amount ($)" name="processing_fixed_fee" form={form} setForm={setForm}/></div><Toggle label="Use processing estimate for internal margin protection" name="processing_enabled" form={form} setForm={setForm}/><p className="text-xs text-muted-foreground">Processing cost stays internal and is never shown as a customer surcharge.</p></Card>
      <Card className="space-y-4 p-6"><h2 className="text-lg font-bold">S&S Shipping</h2><p className="text-sm text-muted-foreground">S&S fulfillment keeps its own shipping rules. Blank fallback tiers block checkout instead of silently charging $0.</p><Toggle label="S&S fallback shipping enabled" name="ss_shipping_enabled" form={form} setForm={setForm}/><div className="grid gap-4 md:grid-cols-3"><Field label="Free freight threshold ($)" name="ss_free_freight_threshold" form={form} setForm={setForm}/><Field label="1–2 garments ($)" name="ss_tier_1_2" form={form} setForm={setForm}/><Field label="3–5 garments ($)" name="ss_tier_3_5" form={form} setForm={setForm}/><Field label="6–12 garments ($)" name="ss_tier_6_12" form={form} setForm={setForm}/><Field label="13+ garments ($)" name="ss_tier_13_plus" form={form} setForm={setForm}/><Field label="Shipping buffer ($)" name="ss_shipping_buffer" form={form} setForm={setForm}/></div></Card>
      <Card className="space-y-5 p-6"><div><p className="text-xs font-bold tracking-widest text-muted-foreground">HC APPAREL SHIPPING</p><h2 className="mt-1 text-lg font-bold">USPS fulfillment settings</h2><p className="text-sm text-muted-foreground">Enter the actual HC Apparel fulfillment origin and package defaults. These settings never affect S&S fulfillment.</p></div>
        <div className="grid gap-4 md:grid-cols-3"><Field label="Fulfillment origin street" name="origin_street" form={form} setForm={setForm}/><Field label="City" name="origin_city" form={form} setForm={setForm}/><Field label="State" name="origin_state" form={form} setForm={setForm}/><Field label="ZIP" name="origin_zip" form={form} setForm={setForm}/><Field label="Default product weight" name="default_product_weight_oz" form={form} setForm={setForm} note="Used only when a product has no weight."/><Unit label="Weight unit" name="default_product_weight_unit" form={form} setForm={setForm} options={weightUnits}/><Field label="Default package length" name="default_package_length_in" form={form} setForm={setForm}/><Field label="Default package width" name="default_package_width_in" form={form} setForm={setForm}/><Field label="Default package height" name="default_package_height_in" form={form} setForm={setForm}/><Unit label="Dimension unit" name="default_package_dimension_unit" form={form} setForm={setForm} options={dimensionUnits}/><Field label="Fallback flat shipping amount ($)" name="hc_fallback_rate" form={form} setForm={setForm}/><Field label="Optional handling amount ($)" name="hc_handling_amount" form={form} setForm={setForm}/><Field label="Optional free shipping threshold ($)" name="hc_free_shipping_threshold" form={form} setForm={setForm}/></div>
        <div className="grid gap-3 sm:grid-cols-2"><Toggle label="USPS live rates enabled" name="usps_enabled" form={form} setForm={setForm}/><Toggle label="Ground Advantage enabled" name="usps_ground_advantage_enabled" form={form} setForm={setForm}/><Toggle label="Priority Mail enabled" name="usps_priority_mail_enabled" form={form} setForm={setForm}/><Toggle label="Fallback enabled" name="hc_fallback_enabled" form={form} setForm={setForm}/><Toggle label="Optional free shipping enabled" name="hc_free_shipping_enabled" form={form} setForm={setForm}/></div>
        <div className="space-y-4 rounded-xl border bg-background p-4"><div><h3 className="font-bold">Test USPS Rates</h3><p className="text-sm text-muted-foreground">Read-only pricing test. It creates no order, payment, or label.</p></div><div className="grid gap-4 md:grid-cols-4"><Field label="Destination ZIP" name="destination_zip" form={test} setForm={setTest}/><NumberField label="Package weight" name="weight" form={test} setForm={setTest}/><Unit label="Weight unit" name="weight_unit" form={test} setForm={setTest} options={weightUnits}/><NumberField label="Length" name="length" form={test} setForm={setTest}/><NumberField label="Width" name="width" form={test} setForm={setTest}/><NumberField label="Height" name="height" form={test} setForm={setTest}/><Unit label="Dimension unit" name="dimension_unit" form={test} setForm={setTest} options={dimensionUnits}/></div><Button type="button" variant="outline" onClick={()=>testUsps.mutate()} disabled={testUsps.isPending}>{testUsps.isPending?'Testing USPS…':'Test USPS Rates'}</Button>
          {uspsResult?.error&&<p className="text-sm font-medium text-red-700">{uspsResult.error}</p>}{uspsResult?.oauth?.ok&&<div className="space-y-1 text-sm"><p className="font-semibold text-green-700">USPS OAuth connected · Domestic Pricing HTTP {uspsResult.http_ok?'200':'error'}</p>{(uspsResult.services||[]).map(service=><p key={service.mail_class}>{service.label}: {service.raw_price>0?`$${Number(service.raw_price).toFixed(2)}`:'USPS returned $0.00'}</p>)}<p>Fallback: {uspsResult.fallback?.would_use?`Would use $${Number(uspsResult.fallback.amount).toFixed(2)}`:'Would not be used'}</p>{uspsResult.zero_rate_warning&&<p className="mt-2 rounded-md bg-amber-50 p-2 font-medium text-amber-900">USPS credentials are connected, but USPS returned a zero-dollar production rate. Account/API pricing activation may require review.</p>}</div>}
        </div><p className="text-xs text-muted-foreground">USPS_CLIENT_ID and USPS_CLIENT_SECRET remain in Supabase Edge Function secrets. OAuth tokens and credentials never reach this page.</p></Card>
      <Card className="space-y-4 p-6"><h2 className="text-lg font-bold">Sales tax</h2><Toggle label="Configured tax calculation enabled" name="sales_tax_enabled" form={form} setForm={setForm}/><Field label="Configured tax rate (%)" name="sales_tax_rate_percent" form={form} setForm={setForm}/><p className="text-xs text-muted-foreground">Tax is stored separately and never counted as profit.</p></Card>
      <Button type="submit" disabled={save.isPending}>{save.isPending?'Saving…':'Save pricing & shipping settings'}</Button>
    </form>}</main></div>;
}
