import React, { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertTriangle, ArrowLeft, CheckCircle2, Truck } from 'lucide-react';
import { Link } from 'react-router-dom';
import { toast } from 'sonner';
import { base44 } from '@/api/base44Client';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { DEFAULT_PAYMENT_METHOD_COSTS, normalizePaymentMethodCosts, worstPaymentMethod } from '@/lib/paymentProcessing';

const initial = { id:'default', public_visitor_price_markup_enabled:true, public_visitor_price_difference:5, minimum_margin_per_item:3, processing_enabled:true, processing_percent:6, processing_fixed_fee:.3, payment_method_costs:DEFAULT_PAYMENT_METHOD_COSTS, sales_tax_enabled:false, sales_tax_rate_percent:0, georgia_sales_tax_enabled:true, georgia_tax_method:'destination_based', ss_shipping_enabled:true, ss_free_freight_threshold:200, ss_tier_1_2:'', ss_tier_3_5:'', ss_tier_6_12:'', ss_tier_13_plus:'', ss_shipping_buffer:0, usps_enabled:false, usps_ground_advantage_enabled:true, usps_priority_mail_enabled:true, origin_street:'', origin_city:'', origin_state:'', origin_zip:'', default_product_weight_oz:'', default_product_weight_unit:'oz', default_package_length_in:'', default_package_width_in:'', default_package_height_in:'', default_package_dimension_unit:'in', package_presets:[], hc_fallback_enabled:false, hc_fallback_rate:'', hc_free_shipping_enabled:false, hc_free_shipping_threshold:'', hc_handling_amount:0 };
const numbers = new Set(['public_visitor_price_difference','minimum_margin_per_item','processing_percent','processing_fixed_fee','sales_tax_rate_percent','ss_free_freight_threshold','ss_tier_1_2','ss_tier_3_5','ss_tier_6_12','ss_tier_13_plus','ss_shipping_buffer','default_product_weight_oz','default_package_length_in','default_package_width_in','default_package_height_in','hc_fallback_rate','hc_free_shipping_threshold','hc_handling_amount']);
const testInitial = { destination_zip:'', weight:'', weight_unit:'oz', length:'', width:'', height:'', dimension_unit:'in' };
const weightUnits=[{value:'oz',label:'Ounces (oz)'},{value:'lb',label:'Pounds (lb)'}];
const dimensionUnits=[{value:'in',label:'Inches (in)'},{value:'cm',label:'Centimeters (cm)'}];
function Field({ label, name, form, setForm, note }) { return <label className="block text-sm font-medium">{label}<Input className="mt-1" type={numbers.has(name)?'number':'text'} step={numbers.has(name)?'0.01':undefined} min={numbers.has(name)?'0':undefined} value={form[name]??''} onChange={e=>setForm(v=>({...v,[name]:e.target.value}))}/>{note&&<span className="mt-1 block text-xs font-normal text-muted-foreground">{note}</span>}</label>; }
function NumberField({ label, name, form, setForm }) { return <label className="block text-sm font-medium">{label}<Input className="mt-1" type="number" min="0.01" step="0.01" value={form[name]} onChange={e=>setForm(v=>({...v,[name]:e.target.value}))}/></label>; }
function Toggle({ label, name, form, setForm }) { return <label className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" checked={Boolean(form[name])} onChange={e=>setForm(v=>({...v,[name]:e.target.checked}))}/>{label}</label>; }
function Unit({ label, name, form, setForm, options }) { return <label className="block text-sm font-medium">{label}<select className="mt-1 h-10 w-full rounded-md border bg-background px-3 text-sm" value={form[name]} onChange={e=>setForm(v=>({...v,[name]:e.target.value}))}>{options.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label>; }
const missingValue=value=>value==null||String(value).trim()==='';
const positiveValue=value=>!missingValue(value)&&Number(value)>0;
function ReadinessItem({ label, ready, detail }) { return <div className={`rounded-lg border p-3 ${ready?'border-green-200 bg-green-50':'border-amber-300 bg-amber-50'}`}><div className="flex items-center justify-between gap-3"><p className="font-semibold">{label}</p><span className={`flex items-center gap-1 text-xs font-bold ${ready?'text-green-700':'text-amber-800'}`}>{ready?<CheckCircle2 className="h-4 w-4"/>:<AlertTriangle className="h-4 w-4"/>}{ready?'Ready':'Needs attention'}</span></div><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div>; }
function PackagePresets({value,setForm}) {
  const presets=Array.isArray(value)?value:[];
  const update=(index,patch)=>setForm(current=>({...current,package_presets:presets.map((preset,i)=>i===index?{...preset,...patch}:preset)}));
  const add=()=>setForm(current=>({...current,package_presets:[...(Array.isArray(current.package_presets)?current.package_presets:[]),{id:crypto.randomUUID(),name:'',length:'',width:'',height:'',empty_package_weight:'',dimension_unit:'in',weight_unit:'oz',active:true}]}));
  const remove=index=>setForm(current=>({...current,package_presets:(current.package_presets||[]).filter((_,i)=>i!==index)}));
  return <Card className="space-y-4 p-6"><div><p className="text-xs font-bold tracking-widest text-muted-foreground">HC APPAREL PACKAGE PRESETS</p><h2 className="mt-1 text-lg font-bold">Real package presets</h2><p className="text-sm text-muted-foreground">Optional. Add verified mailers or boxes when needed; no dimensions are guessed.</p></div>{presets.map((preset,index)=><div key={preset.id||index} className="grid gap-3 rounded-xl border p-4 md:grid-cols-4"><label className="text-sm font-medium md:col-span-2">Name<Input className="mt-1" value={preset.name||''} onChange={e=>update(index,{name:e.target.value})}/></label>{['length','width','height','empty_package_weight'].map(key=><label key={key} className="text-sm font-medium">{key==='empty_package_weight'?'Empty package weight':key[0].toUpperCase()+key.slice(1)}<Input className="mt-1" type="number" min="0" step="0.01" value={preset[key]??''} onChange={e=>update(index,{[key]:e.target.value})}/></label>)}<Unit label="Dimension unit" name="dimension_unit" form={preset} setForm={fn=>update(index,fn(preset))} options={dimensionUnits}/><Unit label="Weight unit" name="weight_unit" form={preset} setForm={fn=>update(index,fn(preset))} options={weightUnits}/><label className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" checked={preset.active!==false} onChange={e=>update(index,{active:e.target.checked})}/>Active</label><Button type="button" variant="outline" onClick={()=>remove(index)}>Remove preset</Button></div>)}<Button type="button" variant="outline" onClick={add}>Add package preset</Button></Card>;
}

export default function AdminPaymentFeeSettings() {
  const queryClient=useQueryClient();
  const [form,setForm]=useState(initial);
  const [test,setTest]=useState(testInitial);
  const [uspsResult,setUspsResult]=useState(null);
  const [taxTest,setTaxTest]=useState({destination_city:'Atlanta',destination_zip:'30303',state:'GA'});
  const [taxResult,setTaxResult]=useState(null);
  const [saveStatus,setSaveStatus]=useState(null);
  const {data,isLoading}=useQuery({queryKey:['checkout-financial-settings'],queryFn:async()=>{const result=await base44.functions.invoke('checkout-pricing',{action:'settings_get'}); return result.data.settings;}});
  const record=data;
  useEffect(()=>{if(record)setForm({...initial,...record,payment_method_costs:normalizePaymentMethodCosts(record.payment_method_costs)});},[record]);
  const worstMethod=worstPaymentMethod(form.payment_method_costs);
  const ssMissing=[['Free freight threshold','ss_free_freight_threshold'],['1–2 garment fallback','ss_tier_1_2'],['3–5 garment fallback','ss_tier_3_5'],['6–12 garment fallback','ss_tier_6_12'],['13+ garment fallback','ss_tier_13_plus'],['Shipping buffer','ss_shipping_buffer']].filter(([,key])=>missingValue(form[key])).map(([label])=>label);
  const uspsMissing=[['Fulfillment origin street','origin_street',value=>!missingValue(value)],['City','origin_city',value=>!missingValue(value)],['State','origin_state',value=>!missingValue(value)],['ZIP','origin_zip',value=>/^\d{5}(-\d{4})?$/.test(String(value||'').trim())]].filter(([,key,valid])=>!valid(form[key])).map(([label])=>label);
  const uspsMethodReady=form.usps_ground_advantage_enabled||form.usps_priority_mail_enabled;
  const fallbackReady=!form.hc_fallback_enabled||positiveValue(form.hc_fallback_rate);
  const uspsConnected=Boolean(form._usps_credentials_configured);
  const taxReady=form.georgia_sales_tax_enabled&&form.georgia_tax_method==='destination_based'&&!form._georgia_tax_status?.expired;
  const updatePaymentCost=(key,patch)=>setForm(value=>({...value,payment_method_costs:{...normalizePaymentMethodCosts(value.payment_method_costs),[key]:{...normalizePaymentMethodCosts(value.payment_method_costs)[key],...patch}}}));
  const save=useMutation({mutationFn:async()=>{setSaveStatus(null);const payload=Object.fromEntries(Object.entries(form).filter(([k,v])=>!['id','updated_at','updated_by','origin_name'].includes(k)&&(!numbers.has(k)||v!==''))); return base44.functions.invoke('checkout-pricing',{action:'settings_save',payload});},onSuccess:async result=>{setForm({...initial,...result.data.settings});await queryClient.invalidateQueries({queryKey:['checkout-financial-settings']});setSaveStatus({ok:true,message:'Pricing & shipping settings saved.'});toast.success('Pricing & shipping settings saved.');},onError:e=>{const code=e.code||e.status||'unknown';console.error('Pricing and shipping settings save failed',{code});setSaveStatus({ok:false,message:`Settings could not be saved. Please try again. (Code: ${code})`});toast.error('Settings could not be saved. Please try again.');}});
  const testUsps=useMutation({mutationFn:()=>base44.functions.invoke('checkout-pricing',{action:'usps_rate_test',payload:{origin_zip:form.origin_zip,destination_zip:test.destination_zip,weight:test.weight,weight_unit:test.weight_unit,length:test.length,width:test.width,height:test.height,dimension_unit:test.dimension_unit,ground_enabled:form.usps_ground_advantage_enabled,priority_enabled:form.usps_priority_mail_enabled,fallback_enabled:form.hc_fallback_enabled,fallback_amount:form.hc_fallback_rate}}),onSuccess:result=>{setUspsResult(result.data);toast.success('USPS rate test completed.');},onError:error=>{setUspsResult({error:error.message});toast.error(error.message);}});
  const testTax=useMutation({mutationFn:()=>base44.functions.invoke('checkout-pricing',{action:'georgia_tax_test',payload:taxTest}),onSuccess:result=>setTaxResult(result.data),onError:error=>setTaxResult({error:error.message})});
  return <div className="min-h-screen bg-muted/30"><header className="bg-primary px-4 py-6 text-primary-foreground"><div className="container mx-auto max-w-5xl"><Link to="/AdminDashboard"><Button size="sm" variant="ghost" className="-ml-3 text-primary-foreground"><ArrowLeft className="mr-1 h-4 w-4"/>Admin Dashboard</Button></Link><h1 className="mt-2 flex items-center gap-2 text-2xl font-extrabold"><Truck className="text-accent"/>Pricing & Shipping Settings</h1><p className="mt-1 text-sm text-primary-foreground/70">Server-side checkout rules. Carrier and vendor credentials are never shown here.</p></div></header>
    <main className="container mx-auto max-w-5xl space-y-6 px-4 py-8">{isLoading?<div>Loading settings…</div>:<form className="space-y-6" onSubmit={e=>{e.preventDefault();save.mutate();}}>
      <Card className="space-y-4 p-6"><div><p className="text-xs font-bold tracking-widest text-muted-foreground">CUSTOMER PRICING DISPLAY</p><h2 className="mt-1 text-lg font-bold">Public visitor pricing</h2></div><p className="text-sm text-muted-foreground">Stored Catalog Price: <strong>HC Apparel Customer Price</strong>. Logged-out visitors see the configured difference added to merchandise only; shipping, tax, and printing are unchanged.</p><div className="grid gap-4 sm:grid-cols-2"><Field label="Public Visitor Price Difference ($)" name="public_visitor_price_difference" form={form} setForm={setForm}/><Toggle label="Public visitor price difference enabled" name="public_visitor_price_markup_enabled" form={form} setForm={setForm}/></div></Card>
      <Card className="space-y-4 p-6"><h2 className="text-lg font-bold">Pricing rules & payment processing</h2><div className="grid gap-4 md:grid-cols-3"><Field label="Minimum margin per item ($)" name="minimum_margin_per_item" form={form} setForm={setForm}/><Field label="Processing percentage (%)" name="processing_percent" form={form} setForm={setForm}/><Field label="Fixed transaction amount ($)" name="processing_fixed_fee" form={form} setForm={setForm}/></div><Toggle label="Use processing estimate for internal margin protection" name="processing_enabled" form={form} setForm={setForm}/><p className="text-xs text-muted-foreground">Processing cost stays internal and is never shown as a customer surcharge.</p></Card>
      <Card className="space-y-4 p-6"><div><h2 className="text-lg font-bold">Payment Method Processing Costs</h2><p className="text-sm text-muted-foreground">Admin-only assumptions used to protect product margin. Customers never see a processing or payment-method surcharge.</p></div><div className="grid gap-3 rounded-lg border bg-primary/[0.03] p-4 sm:grid-cols-3"><div><p className="text-xs text-muted-foreground">Worst-case enabled payment method</p><p className="font-semibold">{worstMethod.method?.label || 'None enabled'}</p></div><div><p className="text-xs text-muted-foreground">Worst-case domestic fee</p><p className="font-semibold">{worstMethod.method ? `${Number(worstMethod.method.percentage).toFixed(2)}% + $${Number(worstMethod.method.fixed_fee).toFixed(2)}` : 'Disabled'}</p></div><div><p className="text-xs text-muted-foreground">Pricing floor protection</p><p className="font-semibold">{form.processing_enabled ? 'Enabled' : 'Disabled'}</p></div></div><p className="rounded-md bg-green-50 p-3 text-sm font-medium text-green-900">HC Apparel product pricing protects the configured margin against the highest enabled payment-processing cost.</p><div className="space-y-3">{Object.entries(normalizePaymentMethodCosts(form.payment_method_costs)).map(([key,method])=><div key={key} className="grid gap-3 rounded-lg border bg-background p-3 sm:grid-cols-[minmax(150px,1fr)_120px_120px] sm:items-end"><div><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={method.enabled} onChange={event=>updatePaymentCost(key,{enabled:event.target.checked})}/>{method.label}</label><p className="mt-1 text-xs text-muted-foreground">Last updated: {method.updated_at?new Date(method.updated_at).toLocaleString():'Saved when settings are updated'}</p></div><label className="text-xs font-medium">Percentage (%)<Input className="mt-1" type="number" min="0" max="99" step="0.01" value={method.percentage} onChange={event=>updatePaymentCost(key,{percentage:event.target.value})}/></label><label className="text-xs font-medium">Fixed fee ($)<Input className="mt-1" type="number" min="0" step="0.01" value={method.fixed_fee} onChange={event=>updatePaymentCost(key,{fixed_fee:event.target.value})}/></label></div>)}</div><p className="text-xs text-muted-foreground">The highest enabled solved cost sets the public pricing floor.</p></Card>
      <Card className="space-y-4 p-6"><div><h2 className="text-lg font-bold">Checkout shipping readiness</h2><p className="text-sm text-muted-foreground">These checks identify configuration required before production checkout. Values are never guessed or replaced with $0.</p></div><div className="grid gap-3 md:grid-cols-2"><ReadinessItem label="S&S checkout shipping" ready={!form.ss_shipping_enabled||ssMissing.length===0} detail={!form.ss_shipping_enabled?'Disabled':ssMissing.length?`Missing: ${ssMissing.join(', ')}.`:'Free-freight threshold, all fallback tiers, and buffer are configured.'}/><ReadinessItem label="USPS live rates" ready={form.usps_enabled&&uspsConnected&&uspsMethodReady&&uspsMissing.length===0} detail={`Connection: ${uspsConnected?'Connected':'Not connected'} · Ground Advantage: ${form.usps_ground_advantage_enabled?'Enabled':'Disabled'} · Priority Mail: ${form.usps_priority_mail_enabled?'Enabled':'Disabled'}`}/><ReadinessItem label="HC Apparel package data" ready={uspsMissing.length===0} detail={uspsMissing.length?`Missing required origin data: ${uspsMissing.join(', ')}.`:`Origin ready. Global dimensions are optional; ${(form.package_presets||[]).filter(p=>p.active!==false).length} active package preset(s).`}/><ReadinessItem label="HC Apparel fallback shipping" ready={fallbackReady} detail={`Fallback: ${form.hc_fallback_enabled?'Enabled':'Disabled'} · Amount: ${positiveValue(form.hc_fallback_rate)?`$${Number(form.hc_fallback_rate).toFixed(2)}`:'Not configured'}`}/></div>{form.ss_shipping_enabled&&ssMissing.length>0&&<p className="rounded-md bg-amber-50 p-3 text-sm font-semibold text-amber-900">S&S checkout shipping configuration incomplete. Enter: {ssMissing.join(', ')}.</p>}{form.usps_enabled&&uspsMissing.length>0&&<p className="rounded-md bg-amber-50 p-3 text-sm font-semibold text-amber-900">HC Apparel USPS origin is incomplete. Enter: {uspsMissing.join(', ')}.</p>}{form.hc_fallback_enabled&&!fallbackReady&&<p className="rounded-md bg-amber-50 p-3 text-sm font-semibold text-amber-900">USPS fallback is enabled, but the fallback shipping amount is missing.</p>}</Card>
      <Card className="space-y-4 p-6"><h2 className="text-lg font-bold">S&S Shipping</h2><p className="text-sm text-muted-foreground">S&S fulfillment keeps its own shipping rules. Blank fallback tiers block checkout instead of silently charging $0.</p><Toggle label="S&S fallback shipping enabled" name="ss_shipping_enabled" form={form} setForm={setForm}/><div className="grid gap-4 md:grid-cols-3"><Field label="Free freight threshold ($)" name="ss_free_freight_threshold" form={form} setForm={setForm}/><Field label="1–2 garments ($)" name="ss_tier_1_2" form={form} setForm={setForm}/><Field label="3–5 garments ($)" name="ss_tier_3_5" form={form} setForm={setForm}/><Field label="6–12 garments ($)" name="ss_tier_6_12" form={form} setForm={setForm}/><Field label="13+ garments ($)" name="ss_tier_13_plus" form={form} setForm={setForm}/><Field label="Shipping buffer ($)" name="ss_shipping_buffer" form={form} setForm={setForm}/></div></Card>
      <Card className="space-y-5 p-6"><div><p className="text-xs font-bold tracking-widest text-muted-foreground">HC APPAREL SHIPPING</p><h2 className="mt-1 text-lg font-bold">USPS fulfillment settings</h2><p className="text-sm text-muted-foreground">Actual product/SKU weight and dimensions are used first. Global fallback values are optional and never required when USPS returns a valid weight-only rate. These settings never affect S&amp;S fulfillment.</p></div>
        <div className="grid gap-4 md:grid-cols-3"><Field label="Fulfillment origin street" name="origin_street" form={form} setForm={setForm}/><Field label="City" name="origin_city" form={form} setForm={setForm}/><Field label="State" name="origin_state" form={form} setForm={setForm}/><Field label="ZIP" name="origin_zip" form={form} setForm={setForm}/><Field label="Default product weight" name="default_product_weight_oz" form={form} setForm={setForm} note="Used only when a product has no weight."/><Unit label="Weight unit" name="default_product_weight_unit" form={form} setForm={setForm} options={weightUnits}/><Field label="Default package length" name="default_package_length_in" form={form} setForm={setForm}/><Field label="Default package width" name="default_package_width_in" form={form} setForm={setForm}/><Field label="Default package height" name="default_package_height_in" form={form} setForm={setForm}/><Unit label="Dimension unit" name="default_package_dimension_unit" form={form} setForm={setForm} options={dimensionUnits}/><Field label="Fallback flat shipping amount ($)" name="hc_fallback_rate" form={form} setForm={setForm}/><Field label="Optional handling amount ($)" name="hc_handling_amount" form={form} setForm={setForm}/><Field label="Optional free shipping threshold ($)" name="hc_free_shipping_threshold" form={form} setForm={setForm}/></div>
        <div className="grid gap-3 sm:grid-cols-2"><Toggle label="USPS live rates enabled" name="usps_enabled" form={form} setForm={setForm}/><Toggle label="Ground Advantage enabled" name="usps_ground_advantage_enabled" form={form} setForm={setForm}/><Toggle label="Priority Mail enabled" name="usps_priority_mail_enabled" form={form} setForm={setForm}/><Toggle label="Fallback enabled" name="hc_fallback_enabled" form={form} setForm={setForm}/><Toggle label="Optional free shipping enabled" name="hc_free_shipping_enabled" form={form} setForm={setForm}/></div>
        <div className="space-y-4 rounded-xl border bg-background p-4"><div><h3 className="font-bold">Test USPS Rates</h3><p className="text-sm text-muted-foreground">Read-only pricing test. It creates no order, payment, or label.</p></div><div className="grid gap-4 md:grid-cols-4"><Field label="Destination ZIP" name="destination_zip" form={test} setForm={setTest}/><NumberField label="Package weight" name="weight" form={test} setForm={setTest}/><Unit label="Weight unit" name="weight_unit" form={test} setForm={setTest} options={weightUnits}/><NumberField label="Length" name="length" form={test} setForm={setTest}/><NumberField label="Width" name="width" form={test} setForm={setTest}/><NumberField label="Height" name="height" form={test} setForm={setTest}/><Unit label="Dimension unit" name="dimension_unit" form={test} setForm={setTest} options={dimensionUnits}/></div><Button type="button" variant="outline" onClick={()=>testUsps.mutate()} disabled={testUsps.isPending}>{testUsps.isPending?'Testing USPS…':'Test USPS Rates'}</Button>
          {uspsResult?.error&&<p className="text-sm font-medium text-red-700">{uspsResult.error}</p>}{uspsResult?.oauth?.ok&&<div className="space-y-1 text-sm"><p className="font-semibold text-green-700">USPS OAuth connected · Domestic Pricing HTTP {uspsResult.http_ok?'200':'error'}</p>{(uspsResult.services||[]).map(service=><p key={service.mail_class}>{service.label}: {service.raw_price==null?'Price unavailable':service.raw_price>0?`$${Number(service.raw_price).toFixed(2)}`:'USPS returned $0.00'}</p>)}<p>Fallback: {uspsResult.fallback?.would_use?`Would use $${Number(uspsResult.fallback.amount).toFixed(2)}`:'Would not be used'}</p>{uspsResult.zero_rate_warning&&<p className="mt-2 rounded-md bg-amber-50 p-2 font-medium text-amber-900">USPS credentials are connected, but USPS returned a zero-dollar production rate. Account/API pricing activation may require review.</p>}{uspsResult.diagnostics&&<details className="mt-3 rounded-md border p-3"><summary className="cursor-pointer font-semibold">Sanitized USPS response diagnostics</summary><pre className="mt-2 max-h-96 overflow-auto whitespace-pre-wrap break-words text-xs">{JSON.stringify(uspsResult.diagnostics,null,2)}</pre></details>}</div>}
        </div><p className="text-xs text-muted-foreground">USPS_CLIENT_ID and USPS_CLIENT_SECRET remain in Supabase Edge Function secrets. OAuth tokens and credentials never reach this page.</p></Card>
      <PackagePresets value={form.package_presets} setForm={setForm}/>
      <Card className="space-y-4 p-6"><div><h2 className="text-lg font-bold">Georgia Sales Tax</h2><p className="text-sm text-muted-foreground">Destination-based Georgia tax uses the delivery city and ZIP. No flat statewide rate is used, and non-Georgia destinations receive $0 Georgia tax.</p></div><Toggle label="Georgia Sales Tax: Enabled" name="georgia_sales_tax_enabled" form={form} setForm={setForm}/><div className="grid gap-3 rounded-lg border p-4 text-sm sm:grid-cols-2"><p><span className="text-muted-foreground">Method:</span> <strong>Destination based</strong></p><p><span className="text-muted-foreground">Last tax-rate update:</span> <strong>{form._georgia_tax_status?.last_tax_rate_update||'Not loaded'}</strong></p><p><span className="text-muted-foreground">Effective through:</span> <strong>{form._georgia_tax_status?.effective_through||'Not loaded'}</strong></p><p><span className="text-muted-foreground">Rate source:</span> <strong>{form._georgia_tax_status?.rate_source||'Not loaded'}</strong></p></div>{!taxReady&&<p className="rounded-md bg-amber-50 p-3 text-sm font-semibold text-amber-900">Georgia rate configuration is disabled, missing, or past its effective period. Update the server-side rate source before accepting a Georgia checkout.</p>}<div className="rounded-xl border p-4"><h3 className="font-bold">Test destination tax</h3><p className="mb-3 text-sm text-muted-foreground">Read-only. Creates no order or payment.</p><div className="grid gap-3 sm:grid-cols-3"><Field label="City" name="destination_city" form={taxTest} setForm={setTaxTest}/><Field label="ZIP" name="destination_zip" form={taxTest} setForm={setTaxTest}/><Field label="State" name="state" form={taxTest} setForm={setTaxTest}/></div><Button className="mt-3" type="button" variant="outline" onClick={()=>testTax.mutate()} disabled={testTax.isPending}>Test Georgia Tax</Button>{taxResult&&<div className={`mt-3 rounded-md p-3 text-sm ${taxResult.ok?'bg-green-50 text-green-900':'bg-amber-50 text-amber-900'}`}>{taxResult.error||taxResult.message||`${taxResult.jurisdiction_name||'Non-Georgia destination'} · ${Number(taxResult.rate_percent||0).toFixed(2)}%`}</div>}</div><p className="text-xs text-muted-foreground">Tax collected is stored separately from merchandise revenue and never counted as profit.</p></Card>
      <div className="space-y-2"><Button type="submit" disabled={save.isPending}>{save.isPending?'Saving…':'Save pricing & shipping settings'}</Button>{saveStatus&&<p role="status" className={`text-sm font-medium ${saveStatus.ok?'text-green-700':'text-red-700'}`}>{saveStatus.message}</p>}</div>
    </form>}</main></div>;
}
