import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
const [page,calendar,weekly,migration,baselineMigration,campaignMigration,contentMigration,weeklyMigration,socialMigration,metaScheduleMigration,artworkMigration,analytics,confirmation,newsletter,tracker,cart,checkout,app,dashboard,layout]=await Promise.all([
 readFile(new URL('../src/pages/AdminMarketingCenter.jsx',import.meta.url),'utf8'),readFile(new URL('../src/components/marketing/MarketingContentCalendar.jsx',import.meta.url),'utf8'),readFile(new URL('../src/components/marketing/WeeklyOrganicReview.jsx',import.meta.url),'utf8'),readFile(new URL('../supabase/migrations/202609280001_build_organic_marketing_center.sql',import.meta.url),'utf8'),readFile(new URL('../supabase/migrations/202609280002_establish_marketing_analytics_baseline.sql',import.meta.url),'utf8'),readFile(new URL('../supabase/migrations/202609280003_create_first_organic_marketing_campaign.sql',import.meta.url),'utf8'),readFile(new URL('../supabase/migrations/202609280004_prepare_organic_launch_content_packs.sql',import.meta.url),'utf8'),readFile(new URL('../supabase/migrations/202609280005_add_weekly_organic_marketing_review.sql',import.meta.url),'utf8'),readFile(new URL('../supabase/migrations/202609290001_update_marketing_social_accounts.sql',import.meta.url),'utf8'),readFile(new URL('../supabase/migrations/202609290002_remove_inactive_meta_from_calendar.sql',import.meta.url),'utf8'),readFile(new URL('../supabase/migrations/202609290003_add_mobile_marketing_artwork_drafts.sql',import.meta.url),'utf8'),readFile(new URL('../src/lib/marketingAnalytics.js',import.meta.url),'utf8'),readFile(new URL('../src/pages/OrderConfirmation.jsx',import.meta.url),'utf8'),readFile(new URL('../src/components/marketing/NewsletterSignup.jsx',import.meta.url),'utf8'),readFile(new URL('../src/lib/NavigationTracker.jsx',import.meta.url),'utf8'),readFile(new URL('../src/components/shop/CartContext.jsx',import.meta.url),'utf8'),readFile(new URL('../src/pages/Checkout.jsx',import.meta.url),'utf8'),readFile(new URL('../src/App.jsx',import.meta.url),'utf8'),readFile(new URL('../src/pages/AdminDashboard.jsx',import.meta.url),'utf8'),readFile(new URL('../src/Layout.jsx',import.meta.url),'utf8')]);
const jacketsMigration=await readFile(new URL('../supabase/migrations/202609290006_add_jackets_without_hoods_marketing_drafts.sql',import.meta.url),'utf8');
const pinterestPlanMigration=await readFile(new URL('../supabase/migrations/202610080001_create_october_pinterest_sales_plan.sql',import.meta.url),'utf8');
const jacketsArtwork=await readFile(new URL('../public/marketing/hc-apparel-organic-launch/jackets-without-hoods.jpg',import.meta.url));
for(const tab of ['Overview','Marketing Plan','Action Plan','Performance','Weekly Review','Content Calendar','SEO & GEO','Social Content','Email Marketing','Google Business','Competitors','Settings'])assert.match(page,new RegExp(tab.replace(/[&]/g,'&')));
assert.match(migration,/monthly_paid_budget numeric\(12,2\) not null default 0/);
assert.match(migration,/marketing_settings_paid_budget_guard/);
assert.match(migration,/paid_advertising_enabled = false/);
assert.match(migration,/Complete Google Business verification/);
assert.match(migration,/Build local outreach prospect categories/);
for(const table of ['marketing_channels','marketing_tasks','marketing_campaigns','marketing_social_content','marketing_email_campaigns','marketing_google_business_items','marketing_competitors','marketing_goals','marketing_seo_pages','marketing_content_ideas'])assert.match(migration,new RegExp(table));
for(const event of ['page_view','product_view','brand_view','category_view','account_signup','login','add_to_cart','remove_from_cart','checkout_started','shipping_quote_success','payment_method_selected','purchase_completed','quote_request_submitted','contact_submitted','email_subscribed','sale_promo_clicked','search_used','track_order_used'])assert.match(`${migration}\n${page}`,new RegExp(event));
assert.match(tracker,/product_view/);assert.match(tracker,/brand_view/);assert.match(tracker,/category_view/);assert.match(checkout,/checkout_started/);assert.match(cart,/remove_from_cart/);assert.match(checkout,/shipping_quote_success/);
assert.match(app,/path="\/AdminMarketingCenter"/);assert.match(dashboard,/Marketing Center/);assert.match(layout,/Marketing Center/);
assert.match(baselineMigration,/analytics_reliable_since/);assert.match(baselineMigration,/marketing_analytics_health/);assert.match(page,/Tracking reliable since:/);assert.match(page,/Historical Analytics/);assert.match(page,/Reliable for funnel/);assert.match(page,/purchases:count\('purchase_completed'\)/);assert.match(page,/m\.checkout>m\.cart/);
assert.match(campaignMigration,/HC Apparel Organic Launch/);assert.match(campaignMigration,/hc_apparel_organic_launch/);assert.match(campaignMigration,/status='Draft'/);assert.match(campaignMigration,/2026-09-28 12:23:15\+00/);assert.equal((campaignMigration.match(/\('2026-\d\d-\d\d'::date|'2026-\d\d-\d\d'/g)||[]).length>6,true);for(const source of ['google_business','instagram','facebook','tiktok','email'])assert.match(campaignMigration,new RegExp(`utm_source=.*${source}|${source}.*organic`));
for(const channel of ['Google Business Profile','Facebook','Instagram','TikTok / Reels','Email','SEO / GEO','Local Outreach'])assert.match(campaignMigration,new RegExp(channel.replace('/','\\/')));
assert.match(analytics,/log_marketing_event_v3/);assert.match(analytics,/sessionStorage/);assert.match(analytics,/utm_campaign/);assert.match(confirmation,/attributeMarketingPurchase/);assert.match(newsletter,/email_subscribed/);assert.match(page,/OrganicLaunchCampaign/);assert.match(page,/OrganicLaunchDrafts/);
for(const field of ['short_caption','recommended_image_url','image_video_concept','recommended_format','recommended_dimensions','video_hook','shot_list','on_screen_text','script_idea','suggested_duration','assigned_to','email_subject','email_preview_text','email_heading','email_body','cta_button_copy','published_url','published_date'])assert.match(contentMigration,new RegExp(field));
for(const status of ['Idea','Draft','Ready to Publish','Published','Archived','Needs Update'])assert.match(contentMigration,new RegExp(status));
for(const filter of ['Facebook','Instagram','TikTok','Google Business','Email','SEO','Local Outreach'])assert.match(page,new RegExp(filter));
assert.match(page,/ContentCalendar/);assert.match(page,/Complete Content Packs/);assert.match(page,/3-second hook:/);assert.match(page,/UTM tracking link/);assert.match(contentMigration,/status='Draft'/);assert.match(contentMigration,/utm_campaign=hc_apparel_organic_launch/);
assert.doesNotMatch(contentMigration,/insert into public\.marketing_campaigns/i);
for(const text of ['Weekly Organic Marketing Review','Last 7 Days','Previous 7 Days','30 Days','Channel Performance','Content Performance','Product Performance','Reliable Funnel','Weekly Insights','Recommended Next Week','Prepare Next Week','Approval Checklist & Content Results','Platform-reported engagement'])assert.match(weekly,new RegExp(text.replace(/[&]/g,'&')));
for(const channel of ['Google Business','Facebook','Instagram','TikTok','Email','SEO / Organic Search','Local Outreach','Direct / Unknown'])assert.match(weekly,new RegExp(channel.replace('/','\\/')));
for(const field of ['product_active_verified','price_verified','link_verified','utm_link_verified','media_selected','caption_reviewed','cta_reviewed','sale_status_verified','platform_views','platform_likes','platform_comments','platform_shares','platform_saves','generation_week_start','generated_from_review'])assert.match(weeklyMigration,new RegExp(field));
assert.match(weeklyMigration,/enforce_marketing_content_readiness/);assert.match(weeklyMigration,/log_marketing_event_v3/);assert.match(weeklyMigration,/'order_id',p_order_id,'revenue'/);assert.match(analytics,/log_marketing_event_v3/);assert.match(checkout,/product_ids/);assert.match(checkout,/cart_quantity/);assert.doesNotMatch(tracker,/checkout_started/);
assert.match(weekly,/status:'Draft'/);assert.match(weekly,/hc_apparel_organic_launch/);assert.match(weekly,/No duplicate drafts were created/);assert.match(weekly,/Nothing was published/);assert.doesNotMatch(weeklyMigration,/insert into public\.marketing_campaigns/i);
assert.match(socialMigration,/create table if not exists public\.marketing_social_accounts/);
for(const platform of ['TikTok','X','Pinterest','LinkedIn','YouTube Shorts','Facebook','Instagram'])assert.match(socialMigration,new RegExp(`'${platform}'`));
assert.match(socialMigration,/@ilovehcapparel/);assert.match(socialMigration,/https:\/\/www\.tiktok\.com\/@ilovehcapparel/);assert.match(socialMigration,/https:\/\/x\.com\/ilovehcapparel/);
for(const pair of ["'tiktok','organic_social'","'x','organic_social'","'pinterest','organic_social'","'youtube','organic_video'","'linkedin','organic_social'"])assert.match(socialMigration,new RegExp(pair));
assert.match(socialMigration,/Create first TikTok product video/);assert.match(socialMigration,/Adapt approved TikTok video for YouTube Shorts/);assert.match(socialMigration,/Create X sports and team apparel post/);
assert.match(page,/Social Accounts/);assert.match(calendar,/Published URL/);assert.match(page,/marketing_social_accounts/);assert.match(page,/socialAccounts=\{d\.accounts\}/);
assert.match(page,/tab==='Content Calendar'&&<MarketingContentCalendar/);
assert.match(page,/\{key:'social-content',label:'Social Content'\},\s*\{key:'content-calendar',label:'Content Calendar'\},\s*\{key:'email-marketing',label:'Email Marketing'\}/);
assert.match(page,/data-tab-key=\{x\.key\}/);assert.match(page,/lg:flex-wrap/);assert.match(page,/Scroll tabs/);
for(const text of ["Today's Content",'October 9–22 Pinterest Sales Plan','Content Calendar','Day / Date','Platform / Account','Open / Review'])assert.match(calendar,new RegExp(text.replace(/[']/g,"\\'")));
assert.match(calendar,/activePlatforms/);assert.match(calendar,/Historical \/ Inactive Channels/);
assert.match(metaScheduleMigration,/original_platform/);assert.match(metaScheduleMigration,/active_schedule=false/);assert.match(metaScheduleMigration,/status=case when status='Published' then status else 'Archived' end/);assert.doesNotMatch(metaScheduleMigration,/insert into public\.marketing_social_content/i);
assert.match(weekly,/platformAttribution/);assert.match(weekly,/activeSocial/);assert.doesNotMatch(weekly,/const defaults=\['Instagram','Facebook'/);
for(const filter of ['TikTok','X','Pinterest','LinkedIn','YouTube Shorts','Google Business','Email','SEO / GEO','Local Outreach'])assert.match(calendar,new RegExp(filter.replace('/','\\/')));
for(const key of ['outerwear_puffers_pinterest','outerwear_puffers_x','outerwear_rain_jackets_pinterest','outerwear_rain_jackets_x','outerwear_overview_pinterest','outerwear_overview_x'])assert.match(artworkMigration,new RegExp(key));
for(const action of ['Upload / replace artwork','Download Image','Copy Caption','Mark as posted'])assert.match(calendar,new RegExp(action));
for(const action of ['Copy Title','Copy Description','Copy Link','Open Pinterest'])assert.match(calendar,new RegExp(action));
assert.match(calendar,/localStorage/);assert.match(calendar,/beforeunload/);assert.match(calendar,/object-contain/);assert.match(calendar,/type="file"/);
assert.match(artworkMigration,/status='Draft'/);assert.match(artworkMigration,/image_alt_text/);assert.match(artworkMigration,/media_storage_path/);assert.match(artworkMigration,/ShopGarments\?type=outerwear/);
for(const key of ['jackets_without_hoods_tiktok','jackets_without_hoods_pinterest'])assert.match(jacketsMigration,new RegExp(key));
for(const platform of ["'TikTok'","'Pinterest'"])assert.match(jacketsMigration,new RegExp(platform));
assert.match(jacketsMigration,/ShopGarments\?type=outerwear/);
assert.match(jacketsMigration,/CH416, which is not currently published/);
assert.match(jacketsMigration,/status='Draft'/);
assert.doesNotMatch(jacketsMigration,/status='Published'|paid_advertising_enabled\s*=\s*true|insert into public\.marketing_campaigns/i);
assert.equal(createHash('sha256').update(jacketsArtwork).digest('hex'),'99696a7fca223eab7e26d0c0f3ca0746c9d4330fdd399981676ff4c137cf7a06');
for(const key of ['oct09_puffers_insulated','oct10_gildan_5000','oct11_blank_hoodies_fall','oct12_comfort_colors_1717','oct13_berne_ch416','oct14_crewneck_sweatshirts','oct15_brand_creators','oct16_rain_jackets','oct17_bella_canvas_3001','oct18_shaka_wear_tees','oct19_american_apparel_2001','oct20_workwear_outerwear','oct21_teams_groups','oct22_fall_apparel_roundup'])assert.match(pinterestPlanMigration,new RegExp(key));
assert.match(pinterestPlanMigration,/planned_time='20:00:00'::time/);
assert.match(pinterestPlanMigration,/planned_timezone='America\/New_York'/);
assert.match(pinterestPlanMigration,/pinterest_board='Apparel Blanks'/);
assert.match(pinterestPlanMigration,/schedule_status='Planned'/);
assert.match(pinterestPlanMigration,/Scheduled on Pinterest/);
assert.match(pinterestPlanMigration,/schedule_confirmation_id/);
assert.match(pinterestPlanMigration,/enforce_confirmed_pinterest_schedule/);
assert.match(pinterestPlanMigration,/publishing_service='Buffer'/);
assert.match(pinterestPlanMigration,/available_boards=array\['Apparel Blanks','Custom Printing'\]/);
assert.match(pinterestPlanMigration,/schedule_batch=pieces\.batch_number/);
assert.doesNotMatch(pinterestPlanMigration,/set\s+schedule_status='Scheduled on Pinterest'|set\s+status='Published'|paid_advertising_enabled\s*=\s*true/i);
assert.match(calendar,/pinterest_october_sales_2026/);
assert.match(calendar,/initial posting-time experiment/);
assert.match(calendar,/Pinterest-native metrics remain unavailable/);
assert.match(weekly,/activeRecommendationPlatforms/);assert.match(weekly,/account.status==='Active'&&activeRecommendationPlatforms.has/);
assert.match(weekly,/currentChannels=channels\.filter/);assert.match(weekly,/Current active channels only/);
assert.doesNotMatch(socialMigration,/insert into public\.marketing_campaigns/i);
assert.doesNotMatch(page,/publish\(|sendEmail|checkout\.sessions|api\.ssactivewear|USPS_CLIENT_SECRET|STRIPE_/i);
assert.doesNotMatch(calendar,/sendEmail|checkout\.sessions|api\.ssactivewear|USPS_CLIENT_SECRET|STRIPE_|paid_advertising_enabled\s*=\s*true/i);
assert.doesNotMatch(weekly,/sendEmail|checkout\.sessions|api\.ssactivewear|USPS_CLIENT_SECRET|STRIPE_|paid_advertising_enabled\s*=\s*true/i);
console.log('PASS: organic-first Marketing Center, $0 paid guardrail, persistence model, admin navigation, and safe analytics coverage.');
console.log('SAFETY: no post, email, ad, payment, S&S order, or USPS label action is present.');
