import assert from 'node:assert/strict';
import fs from 'node:fs';
import {
  artworkQualityReport, artworkSizeForUnit, calculatePrintingCharge, calculateStudioPricing, createStudioDocument, effectiveDpi, historyReducer,
  initializeArtworkSizing, isRestrictedCustomizationProduct, makeElement, normalizedFileKind,
  synchronizeArtworkResize, updateArtworkDimension, validateDesign, validatePlacement,
} from '../src/lib/designStudio.js';
import {
  buildMockupViews, getStudioCustomizationColors, getStudioGarmentLabel, getStudioGarmentType, getVariantImage, isStudioEligibleProduct,
  placementAvailability, previewPhysicalScale, previewSurface,
} from '../src/lib/designStudioCatalog.js';

const document = createStudioDocument({
  productId: 'gildan-5000', color: 'Black', size: 'L', quantity: 2,
  placements: { front: [makeElement('image', { pixelWidth: 1800, pixelHeight: 1680, width: 50, height: 40 })] },
});
const area = { placement: 'front', verified: true, enabled: true, width_in: 12, height_in: 14, min_dpi: 300 };
assert.equal(effectiveDpi(document.placements.front[0], area), 300, 'effective DPI uses physical artwork width');
assert.deepEqual(validatePlacement(document.placements.front, area), [], 'valid placement passes');
assert.ok(validatePlacement([{ ...document.placements.front[0], x: 80 }], area).some(item => item.code === 'outside_print_area'), 'out-of-bounds artwork blocks production');
assert.ok(validatePlacement(document.placements.front, { ...area, verified: false }).some(item => item.code === 'print_area_unverified'), 'unverified physical area blocks production');
assert.deepEqual(validateDesign(document, [area]), [], 'complete design passes configured checks');
const quality = artworkQualityReport({ type: 'image', pixelWidth: 1800, pixelHeight: 1800, intendedWidthIn: 12, intendedHeightIn: 12 }, null, 300);
assert.equal(quality.effectivePpi, 150, 'quality report uses actual pixels divided by intended physical size');
assert.equal(quality.state, 'low', '1800px at 12 inches is low at a 300 PPI target');
assert.equal(quality.maxWidth, 6, 'quality report gives the non-upscaled 300 PPI maximum width');
const screenshotQuality = artworkQualityReport({ type: 'image', pixelWidth: 512, pixelHeight: 255, intendedWidthIn: 4, intendedHeightIn: 2 }, null, 300);
assert.equal(Number(screenshotQuality.maxWidth.toFixed(2)), 1.71, '512px artwork recommends about 1.71 inches at 300 DPI');
assert.equal(Number(screenshotQuality.maxHeight.toFixed(2)), 0.85, '255px artwork recommends 0.85 inches at 300 DPI');
assert.equal(screenshotQuality.label, 'Below 300-DPI minimum—reduce print size or upload higher-resolution artwork.', 'low-resolution status uses the required plain-language warning');
assert.equal(screenshotQuality.effectivePpi, 127, 'effective resolution uses both original pixel axes and selected inches');
const sizingElement = makeElement('image', { pixelWidth: 1800, pixelHeight: 900, width: 50, height: 25 });
const twelveInches = { ...sizingElement, ...updateArtworkDimension(sizingElement, 'width', 12, 'inches', null, 300) };
assert.equal(twelveInches.intendedWidthIn, 12, 'inches are stored as the canonical physical width');
assert.equal(twelveInches.intendedHeightIn, 6, 'aspect lock updates height from the original artwork ratio');
const pixelsView = artworkSizeForUnit({ ...twelveInches, sizeUnit: 'pixels' }, null, 300);
assert.equal(pixelsView.width, 3600, '12 inches displays as 3600 output pixels at the 300 DPI reference');
assert.equal(pixelsView.height, 1800, 'unit switching preserves physical height');
const resized = synchronizeArtworkResize(twelveInches, 25, 12.5, null);
assert.equal(resized.intendedWidthIn, 6, 'canvas resizing updates intended physical width');
assert.equal(resized.intendedHeightIn, 3, 'canvas resizing updates intended physical height');
const approximateScale = previewPhysicalScale(null, 'front');
assert.deepEqual([approximateScale.width_in, approximateScale.height_in, approximateScale.verified], [12, 12, false], 'saved HC service limits provide an explicitly approximate front preview scale');
const initializedArtwork = initializeArtworkSizing(makeElement('image', { pixelWidth: 1000, pixelHeight: 450 }), approximateScale);
assert.equal(initializedArtwork.intendedWidthIn, 6, 'selected artwork immediately receives a physical width from the preview scale');
assert.equal(Number(initializedArtwork.intendedHeightIn.toFixed(2)), 2.7, 'initial physical height follows the original raster aspect ratio');
assert.equal(Number(initializedArtwork.height.toFixed(2)), 22.5, 'the canvas height and physical dimensions share one aspect-correct state');
const typedFourInches = { ...initializedArtwork, ...updateArtworkDimension(initializedArtwork, 'width', 4, 'inches', approximateScale, 300) };
assert.equal(Number(typedFourInches.width.toFixed(2)), 33.33, 'typing inches immediately updates canvas width through the same preview scale');
assert.equal(Number(typedFourInches.intendedHeightIn.toFixed(2)), 1.8, 'aspect lock updates the paired physical dimension');
const movedOnly = { ...typedFourInches, x: typedFourInches.x + 4, y: typedFourInches.y + 2 };
assert.equal(movedOnly.intendedWidthIn, typedFourInches.intendedWidthIn, 'moving artwork does not alter its physical width');
assert.equal(movedOnly.intendedHeightIn, typedFourInches.intendedHeightIn, 'moving artwork does not alter its physical height');
const liveResizedArtwork = { ...typedFourInches, ...synchronizeArtworkResize(typedFourInches, 68.25, 30.7125, approximateScale) };
assert.equal(initializeArtworkSizing(liveResizedArtwork, approximateScale), liveResizedArtwork, 'sub-pixel floating-point noise does not create a second history entry during live resizing');
const packaged = calculatePrintingCharge({ ...document, decorationMethod: 'dtf', productionRoute: 'hc_transfer_press', placements: { front: [makeElement('text')], back: [makeElement('text')] } }, [
  { active: true, production_route: 'hc_transfer_press', print_method: 'dtf', placement: 'front', service_price: 19.99 },
], [{ active: true, method_key: 'dtf', placements: ['front', 'back'], service_price: 34.99 }]);
assert.equal(packaged.unit, 34.99, 'saved front/back package price prevents double-counting individual placements');
assert.equal(packaged.configured, true, 'package covers both placements');

const hc = calculateStudioPricing({ route: 'hc_transfer_press', garmentRetail: 8, printingCharge: 12, quantity: 2, supplierProductionCost: 8, packaging: 1, fees: 2 });
assert.equal(hc.customerMerchandise, 40, 'HC route shows garment and printing separately');
const printify = calculateStudioPricing({ route: 'printify', garmentRetail: 36.99, printingCharge: 12, quantity: 1, supplierProductionCost: 12.65, supplierShipping: 3.99, supplierTax: 1.33, fees: 0 });
assert.equal(printify.customerMerchandise, 36.99, 'Printify route does not double-count HC printing');
assert.equal(Number(printify.estimatedContribution.toFixed(2)), 19.02, 'known Printify costs stay separate from customer retail');
assert.equal(calculateStudioPricing({ route: 'printify', garmentRetail: 30, supplierProductionCost: 12 }).estimatedContribution, null, 'incomplete costs do not claim profit');

assert.equal(isRestrictedCustomizationProduct({ brand: 'Columbia' }), true, 'Columbia customization restriction is preserved');
assert.equal(isRestrictedCustomizationProduct({ name: 'Champion Hoodie' }), true, 'Champion customization restriction is preserved');
assert.equal(isRestrictedCustomizationProduct({ name: 'Gildan 5000' }), false, 'eligible Gildan product is allowed');
const baseProduct = { product_type: 'physical', visibility: 'public', is_active: true, stock: 12, brand: 'Gildan', name: 'Gildan 5000 Heavy Cotton T-Shirt', primary_garment_type: 't_shirts', design_studio_eligible: true, design_studio_garment_type: 't_shirts', design_studio_image_status: 'approved', design_studio_approved_colors: ['Black'], design_studio_front_images: { Black: 'https://www.ssactivewear.com/Images/Color/33476_f_fm.jpg' }, image_url: 'https://www.ssactivewear.com/Images/ModelColor/wrong-model.jpg', size_prices: [{ size: 'Black / L', sku: 'TEST-L', inventory: 12, price: 8, image_url: 'https://www.ssactivewear.com/Images/ModelColor/angled-model.jpg' }, { size: 'Red / L', sku: 'TEST-RED-L', inventory: 12, price: 8, image_url: 'https://www.ssactivewear.com/Images/Color/red_f_fm.jpg' }] };
assert.equal(isStudioEligibleProduct(baseProduct), true, 'live in-stock T-shirts are studio eligible');
assert.equal(getStudioGarmentType({ ...baseProduct, name: 'Gildan 18500 Hoodie', primary_garment_type: 'hoodies', design_studio_garment_type: 'pullover_hoodies' }), 'hoodies', 'explicitly approved pullover hoodies are included');
assert.equal(getStudioGarmentLabel({ ...baseProduct, name: 'Full-Zip Hoodie', design_studio_garment_type: 'zip_hoodies' }), 'Zip hoodie', 'zip classification is explicit rather than inferred from product copy');
assert.equal(getStudioGarmentType({ ...baseProduct, name: 'Gildan 18000 Crewneck', primary_garment_type: 'crewnecks', design_studio_garment_type: 'crewnecks' }), 'crewnecks', 'explicitly approved crewnecks are included');
assert.equal(getStudioGarmentType({ ...baseProduct, name: 'Hooded Puffer Jacket', primary_garment_type: 'hoodies', design_studio_garment_type: null }), '', 'a matching title and storefront classification cannot approve outerwear');
assert.equal(getStudioGarmentType({ ...baseProduct, name: 'Crewneck Windbreaker', primary_garment_type: 'crewnecks', design_studio_garment_type: null }), '', 'a title keyword cannot approve a garment for the Studio');
assert.equal(isStudioEligibleProduct({ ...baseProduct, design_studio_eligible: false }), false, 'products require explicit admin-managed studio eligibility');
assert.equal(isStudioEligibleProduct({ ...baseProduct, design_studio_image_status: 'needs_review' }), false, 'unreviewed garment photographs are excluded from new selection');
assert.equal(isStudioEligibleProduct({ ...baseProduct, design_studio_approved_colors: [] }), false, 'a product approval without an exact-color image approval stays excluded');
assert.equal(isStudioEligibleProduct({ ...baseProduct, design_studio_front_images: {} }), false, 'an approval without an exact reviewed photograph mapping fails closed');
assert.equal(isStudioEligibleProduct({ ...baseProduct, brand: 'Berne' }), false, 'Berne workwear stays outside the authorized studio rollout');
assert.equal(isStudioEligibleProduct({ ...baseProduct, brand: 'Champion' }), false, 'restricted brands remain excluded');
assert.deepEqual(getStudioCustomizationColors(baseProduct), ['Black'], 'only exact-color images approved by an admin enter the customer selector');
assert.equal(getVariantImage(baseProduct, 'Red', 'L'), '', 'an unreviewed color cannot reuse or expose a different garment photograph');
const views = buildMockupViews(baseProduct, 'Black', 'L');
assert.equal(views.front.url, baseProduct.design_studio_front_images.Black, 'picker and canvas use the exact photograph approved for the selected color instead of a variant first-image fallback');
assert.equal(placementAvailability(baseProduct, views).back.enabled, false, 'missing back photos are not fabricated');
assert.equal(previewSurface({ ...baseProduct, primary_garment_type: 'hoodies', design_studio_garment_type: 'pullover_hoodies' }, 'front').height < previewSurface(baseProduct, 'front').height, true, 'hoodie front surface leaves room for the pouch pocket');

assert.equal(normalizedFileKind(new Uint8Array([137,80,78,71,13,10,26,10]), 'image/png'), 'png', 'PNG signature is recognized');
assert.equal(normalizedFileKind(new TextEncoder().encode('<svg width="10" height="10"></svg>'), 'image/svg+xml'), 'svg', 'SVG is recognized');
assert.equal(normalizedFileKind(new TextEncoder().encode('not an image'), 'image/png'), null, 'extension/MIME alone cannot bypass validation');

let history = { past: [], present: createStudioDocument(), future: [] };
history = historyReducer(history, { type: 'set', value: { ...history.present, name: 'Changed' } });
history = historyReducer(history, { type: 'undo' });
assert.equal(history.present.name, 'Untitled design', 'undo restores prior document');
history = historyReducer(history, { type: 'redo' });
assert.equal(history.present.name, 'Changed', 'redo restores changed document');
history = historyReducer(history, { type: 'begin_interaction' });
const beforeDrag = history.present;
history = historyReducer(history, { type: 'transient', value: { ...history.present, name: 'Dragging 1' } });
history = historyReducer(history, { type: 'transient', value: { ...history.present, name: 'Dragging 2' } });
history = historyReducer(history, { type: 'commit_interaction' });
history = historyReducer(history, { type: 'undo' });
assert.equal(history.present.name, beforeDrag.name, 'one Undo restores the complete live resize interaction instead of one pointer-move frame');
history = historyReducer(history, { type: 'redo' });
const pastBeforeNormalization = history.past.length;
const futureBeforeNormalization = history.future.length;
history = historyReducer(history, { type: 'normalize', value: { ...history.present, updatedAt: 'normalized' } });
assert.equal(history.past.length, pastBeforeNormalization, 'background dimension normalization does not add a customer-visible Undo step');
assert.equal(history.future.length, futureBeforeNormalization, 'background dimension normalization preserves Redo history');

const migration = fs.readFileSync(new URL('../supabase/migrations/202610030006_build_design_studio_printify_backup.sql', import.meta.url), 'utf8');
const repairMigration = fs.readFileSync(new URL('../supabase/migrations/202610030007_finish_design_studio_mobile.sql', import.meta.url), 'utf8');
const permissionMigration = fs.readFileSync(new URL('../supabase/migrations/202610030008_design_studio_service_role_permissions.sql', import.meta.url), 'utf8');
const archiveMigration = fs.readFileSync(new URL('../supabase/migrations/202610030009_archive_design_studio_qa_fixtures.sql', import.meta.url), 'utf8');
const mobileActionMigration = fs.readFileSync(new URL('../supabase/migrations/202610030012_repair_design_studio_mobile_actions.sql', import.meta.url), 'utf8');
const vinylMethodMigration = fs.readFileSync(new URL('../supabase/migrations/202610030016_correct_hc_vinyl_methods.sql', import.meta.url), 'utf8');
const artworkSizingMigration = fs.readFileSync(new URL('../supabase/migrations/202610030018_enforce_design_artwork_300_dpi.sql', import.meta.url), 'utf8');
const garmentReviewMigration = fs.readFileSync(new URL('../supabase/migrations/202610030020_explicit_design_studio_garment_review.sql', import.meta.url), 'utf8');
const colorImageReviewMigration = fs.readFileSync(new URL('../supabase/migrations/202610030021_design_studio_color_image_approval.sql', import.meta.url), 'utf8');
const catalogCoverageMigration = fs.readFileSync(new URL('../supabase/migrations/202610040002_expand_design_studio_catalog_coverage.sql', import.meta.url), 'utf8');
const previewCartDedupeMigration = fs.readFileSync(new URL('../supabase/migrations/202610040003_prevent_design_preview_cart_duplicates.sql', import.meta.url), 'utf8');
const edge = fs.readFileSync(new URL('../supabase/functions/design-studio/index.ts', import.meta.url), 'utf8');
const app = fs.readFileSync(new URL('../src/App.jsx', import.meta.url), 'utf8');
const flags = fs.readFileSync(new URL('../src/config/storefrontFeatures.js', import.meta.url), 'utf8');
assert.match(migration, /design_versions_immutable/, 'saved versions are database-immutable');
assert.match(repairMigration, /design_mockup_mappings/, 'real product view mappings are persisted securely');
assert.match(permissionMigration, /grant select, insert, update on public\.design_documents to service_role/, 'server-side private design persistence has an explicit narrow database grant');
assert.match(archiveMigration, /purge_expired_design_studio_test_archives/, 'confirmed Design Studio fixtures follow the six-month purge policy');
assert.match(mobileActionMigration, /design_preview_cart_items/, 'preview cart entries persist server-side instead of browser-local only');
assert.match(mobileActionMigration, /design_decoration_methods/, 'customer methods and internal routes are configured separately');
assert.match(mobileActionMigration, /default_raster_ppi[^;]+default 300/s, 'raster quality target defaults to configurable 300 PPI');
assert.match(vinylMethodMigration, /where method_key in \('dtf','soft_vinyl','puff_vinyl','glitter_vinyl','flock_vinyl'\)/, 'DTF and every HC-operated vinyl method share the HC production update');
assert.match(vinylMethodMigration, /available = true,[\s\S]*production_route = 'hc_transfer_press',[\s\S]*provider_key = 'hc'/, 'HC vinyl production does not depend on an outside vendor');
assert.match(vinylMethodMigration, /draft_selectable = true,[\s\S]*available = false,[\s\S]*where method_key = 'embroidery'/, 'embroidery remains draft-selectable while production is not configured');
assert.match(vinylMethodMigration, /backup_production_route = 'printify'[\s\S]*where method_key = 'dtg'/, 'Printify is only an optional DTG backup route');
assert.doesNotMatch(vinylMethodMigration, /insert into public\.design_pricing_config/i, 'vinyl method correction does not invent or copy customer prices');
assert.match(vinylMethodMigration, /preparation_labor_cost numeric/, 'vinyl internal pricing can account for preparation or weeding labor separately');
assert.match(artworkSizingMigration, /default_raster_ppi between 300 and 1200/, 'raster production readiness cannot be configured below 300 DPI');
assert.match(artworkSizingMigration, /min_dpi between 300 and 1200/, 'verified print-area DPI requirements cannot fall below 300');
assert.match(garmentReviewMigration, /design_studio_eligible boolean not null default false/, 'garments start closed until explicitly approved for the Studio');
assert.match(garmentReviewMigration, /design_studio_garment_type in \([\s\S]*'pullover_hoodies'[\s\S]*'zip_hoodies'/, 'pullover and zip hoodie classifications are stored separately');
assert.match(garmentReviewMigration, /where lower\(brand\) = 'berne'/, 'Berne workwear is explicitly excluded without changing its storefront publication');
assert.match(garmentReviewMigration, /design_studio_image_status = 'approved'/, 'selection requires a reviewed suitable garment photograph');
assert.match(colorImageReviewMigration, /design_studio_approved_colors text\[\]/, 'exact-color garment photograph approvals are persisted separately from product eligibility');
assert.match(colorImageReviewMigration, /cardinality\(design_studio_approved_colors\) > 0/, 'Studio eligibility fails closed without an approved exact-color photograph');
assert.match(catalogCoverageMigration, /design_studio_front_images jsonb not null default '\{\}'::jsonb/, 'exact reviewed front-photo assignments are persisted by color');
assert.match(catalogCoverageMigration, /'gildan', 'comfort colors', 'shaka wear', 'hanes', 'next level'/, 'the rollout includes the requested brand allowlist');
assert.match(catalogCoverageMigration, /every current exact-color supplier image URL failed to render/i, 'styles without a working suitable photograph stay in the review queue with a specific reason');
assert.match(catalogCoverageMigration, /'f2b732d9-0ee6-4fad-9c96-5ed10d7f1fb0',[\s\S]*then 'zip_hoodies'/, 'known zip hoodies are classified explicitly rather than by title matching');
assert.match(migration, /order_design_snapshots_immutable/, 'ordered snapshots are database-immutable');
assert.match(migration, /public_studio_enabled boolean not null default false/, 'public studio starts disabled');
assert.match(migration, /live_vendor_submission_enabled boolean not null default false/, 'vendor submission starts disabled');
assert.match(edge, /payment_verified_at.*artwork_approved_at.*confirm_submission/s, 'submission has payment, artwork, and explicit confirmation gates');
assert.match(edge, /PRINTIFY_API_TOKEN/, 'Printify credential remains server-side');
assert.match(edge, /auth\.auth\.getUser\(jwt\)/, 'server validates the exact bearer token used by the signed-in HC session');
assert.match(edge, /\.\.\.\(payload\.explicit \? \{ status: 'saved'/, 'autosave cannot downgrade an explicitly saved design back to draft');
assert.match(edge, /method\.draft_selectable === false/, 'server separates draft selection from production readiness');
assert.match(edge, /fulfillment_not_configured/, 'preview cart explains outside-provider readiness without blocking draft attachment');
assert.match(edge, /code: 'low_resolution', level: 'blocker'/, 'low-resolution raster artwork blocks production readiness without blocking draft persistence');
assert.match(edge, /action === 'save_catalog_review'/, 'garment and image approval is managed through a server-validated admin setting');
assert.match(edge, /Every approved photograph must exactly match an in-stock catalog color and its supplier image URL/, 'server validates exact-color photo assignments against live imaged variants');
assert.match(edge, /loadEveryProduct\(service/, 'admin coverage scans the catalog with server-side pagination');
assert.match(edge, /studioBrands\.has/, 'server-side selection enforces the requested brand allowlist');
assert.match(edge, /garment_replacement_required/, 'saved designs keep excluded garments as explicit replacement blockers');
assert.doesNotMatch(edge, /hoodie\|hooded sweatshirt\|crewneck/, 'server eligibility no longer falls back to product-title keywords');
assert.match(edge, /enteredWidth[\s\S]*intendedWidthIn[\s\S]*pixelWidth[\s\S]*printWidth/, 'server quality validation uses original upload pixels and selected physical inches');
assert.doesNotMatch(edge, /code: 'method_unavailable'/, 'production readiness is no longer mislabeled as draft method availability');
assert.match(edge, /\.is\('archived_at', null\)\.neq\('status', 'archived'\)/, 'confirmed QA fixtures are excluded from active saved designs by both archive markers');
assert.doesNotMatch(edge, /Deno\.env\.get\([^)]*\).*console\.log/s, 'server secrets are not logged');
assert.match(app, /ProtectedRoute requiredRole="admin"[\s\S]*AdminDesignStudio/, 'preview route is admin protected');
assert.match(app, /path="\/AdminDesignStudio"[\s\S]*AdminDesignStudio customerMode privatePreview/, 'the protected preview renders the customer experience with the isolated preview cart enabled');
assert.match(app, /path="\/AdminDesignStudioAdmin"[\s\S]*<AdminDesignStudio \/>/, 'production, pricing, routing, and coverage controls have a separate admin route');
assert.match(flags, /customPrinting:\s*false/, 'hidden custom-printing page remains hidden');
assert.match(flags, /designStudioPublic:\s*false/, 'public studio flag remains off');
assert.match(app, /path="\/DesignStudio"[\s\S]*STOREFRONT_FEATURES\.designStudioPublic[\s\S]*Navigate to="\/ShopGarments"/, 'customer studio route safely redirects while the public flag is off');

const page = fs.readFileSync(new URL('../src/pages/AdminDesignStudio.jsx', import.meta.url), 'utf8');
assert.match(page, /Choose Garment/, 'garment selection is visible before the canvas');
assert.match(page, /invoke\('catalog'\)/, 'the garment picker uses the authenticated server catalog rather than a broad public-view query');
assert.match(edge, /action === 'catalog'/, 'the server exposes the approved Design Studio catalog independently of the admin coverage report');
assert.match(edge, /loadStudioCatalog\(service/, 'the server paginates the complete approved Studio catalog');
assert.match(edge, /delete safeVariant\[key\]/, 'supplier cost fields are stripped from catalog variants before they reach the Studio');
assert.match(page, /Approved exact-color front photographs/, 'admin coverage provides an exact-photo assignment control');
assert.doesNotMatch(page, /Choose an eligible T-shirt/, 'selector is no longer limited to T-shirts');
assert.match(edge, /action === 'attach_preview_cart'/, 'cart attachment uses the authenticated server workflow');
assert.match(edge, /\.eq\('design_id', design\.id\)[\s\S]*\.is\('archived_at', null\)/, 'reattaching a saved design is deduplicated by active design identity across reloads and versions');
assert.match(edge, /result\.error\?\.code === '23505'/, 'concurrent preview-cart attaches recover from the database uniqueness guard');
assert.match(previewCartDedupeMigration, /unique index[\s\S]*owner_user_id, design_id[\s\S]*where archived_at is null/i, 'the database permits only one active preview-cart row per owner and design');
assert.match(edge, /!isAdmin \|\| payload\.owner_only === true/, 'customer preview saved-design lists remain scoped to the signed-in owner even for an admin testing the customer view');
assert.match(page, /Not checkout-ready/, 'incomplete preview cart entries explain checkout blockers');
assert.doesNotMatch(page, /localStorage\.getItem\('hc_design_preview_cart'/, 'preview cart no longer depends on one browser profile');
assert.match(page, /Print \/ Decoration Method/, 'customers choose a decoration method instead of an internal production vendor');
assert.match(page, /disabled=\{item\.draft_selectable === false\}/, 'method selection is controlled by draft eligibility rather than vendor readiness');
assert.doesNotMatch(page, /Coming soon/, 'customer-facing method names do not contain promotional availability labels');
assert.doesNotMatch(page, /Width %|Height %/, 'customer sizing controls do not expose canvas percentages');
assert.match(page, /Minimum resolution: 300 DPI at the selected print size\./, 'Artwork Quality prominently states the production minimum');
const canvas = fs.readFileSync(new URL('../src/components/design-studio/DesignCanvas.jsx', import.meta.url), 'utf8');
const sizeControls = fs.readFileSync(new URL('../src/components/design-studio/ArtworkSizeControls.jsx', import.meta.url), 'utf8');
const sharedTheme = fs.readFileSync(new URL('../src/index.css', import.meta.url), 'utf8');
const designStudioLib = fs.readFileSync(new URL('../src/lib/designStudio.js', import.meta.url), 'utf8');
assert.match(canvas, /synchronizeArtworkResize\(original, nextWidth, nextHeight, sizingArea\)/, 'live handle resizing updates physical size through the shared preview scale');
assert.match(canvas, /\{ transient: true \}/, 'pointer movement updates the shared document continuously during a drag');
assert.match(canvas, /window\.document\.activeElement\?\.blur\?\.\(\)/, 'starting a canvas gesture releases a focused dimension input so every visible sizing control follows the drag');
assert.match(sizeControls, /Width \(\{suffix\}\)/, 'customer fields explicitly label width units');
assert.match(sizeControls, /Height \(\{suffix\}\)/, 'customer fields explicitly label height units');
assert.match(sizeControls, /editingAxis/, 'decimal typing is preserved while physical dimensions update');
assert.match(sharedTheme, /--primary:\s*82 35% 28%/, 'the shared storefront olive primary remains the Design Studio theme source');
assert.match(sharedTheme, /--accent:\s*44 82% 50%/, 'the shared storefront gold accent remains the Design Studio theme source');
assert.match(page, /bg-primary text-primary-foreground/, 'the Studio header and completed steps use the shared storefront primary token');
assert.match(page, /bg-accent text-accent-foreground/, 'the desktop Save Design action uses the shared storefront accent button treatment');
assert.match(canvas, /stroke="hsl\(var\(--accent\)\)"/, 'canvas selection guides use the shared storefront accent token');
assert.equal(makeElement('text').fill, '#4e602e', 'new customer text layers default to the live storefront primary instead of the retired maroon');
assert.doesNotMatch(`${page}\n${canvas}\n${designStudioLib}`, /#4b1236|#b58d2a|#4f6b45|#f7f3ea|#d8c9b7/i, 'the separate maroon and legacy Studio palette is removed from customer UI and new artwork defaults');
assert.match(page, /setDocument\(\{ \.\.\.document, decorationMethod: value, printMethod: value/, 'switching methods preserves the rest of the editable design document');
assert.match(page, /Vinyl pricing still needs approval/, 'admin pricing identifies missing vinyl configuration without inventing values');
assert.match(page, /aria-label={`Delete \$\{layer\.name\}`}/, 'every layer row has a touch-accessible delete action');
assert.match(page, /Authorization: `Bearer \$\{accessToken\}`/, 'Design Studio sends the active HC session explicitly to its server API');
assert.match(page, /JSON\.stringify\(document\) === savedJsonRef\.current/, 'a stale autosave timer exits after an explicit save');
assert.match(page, /persistDesign\(\{ createVersion: customerMode, busyKey: 'save' \}\)/, 'customer Save Design creates internal immutable history without exposing Save Version');
assert.match(page, /if \(customerMode && !privatePreview\)/, 'customer Add to Cart stays isolated to the authorized private preview until public release');
assert.match(page, /customerMode \? 'Save Design' : 'Save'/, 'the customer action uses the plain Save Design label');
assert.match(page, /customerMode \? <div className="mt-4[\s\S]*Add to Cart[\s\S]*: <div className="mt-4[\s\S]*Download Production Artwork/, 'customer cart action and admin production export render in separate interfaces');

console.log('Design Studio safety, validation, pricing, and persistence tests passed.');
