import assert from 'node:assert/strict';
import fs from 'node:fs';
import { validateCheckoutCart } from '../src/lib/smallOrderCheckout.js';
import { calculateMockupPromotion } from '../src/lib/mockupPromotion.js';

const read = path => fs.readFileSync(new URL(`../${path}`, import.meta.url), 'utf8');
const migration = read('supabase/migrations/202610090001_digital_mockups_storefront.sql');
const mixedMigration = read('supabase/migrations/202610090002_mixed_digital_physical_checkout.sql');
const serviceMigration = read('supabase/migrations/202610090003_digital_mockup_service_permissions.sql');
const testIsolationMigration = read('supabase/migrations/202610090004_digital_mockup_test_order_isolation.sql');
const cleanPreviewMigration = read('supabase/migrations/202610090005_digital_mockup_clean_previews.sql');
const viewPricingMigration = read('supabase/migrations/202610090006_digital_mockup_view_types_and_pricing.sql');
const youthBatchMigration = read('supabase/migrations/202610090008_publish_youth_mockup_batch.sql');
const presentationMigration = read('supabase/migrations/202610090009_digital_mockup_presentation_and_deal.sql');
const edge = read('supabase/functions/digital-mockups/index.ts');
const webhook = read('supabase/functions/stripeWebhook/index.ts');
const checkoutPricing = read('supabase/functions/checkout-pricing/index.ts');
const cart = read('src/components/shop/CartContext.jsx');
const routes = read('src/App.jsx');
const client = read('src/lib/digitalMockups.js');
const downloadsPanel = read('src/components/mockups/DownloadsPanel.jsx');
const storefront = read('src/pages/DigitalMockups.jsx');

const item = { id: 'product-1', product_id: 'product-1', product_name: 'Black T-Shirt Mockup', product_type: 'digital', quantity: 1, price: 0.99 };
assert.equal(item.product_type, 'digital');
assert.equal(item.quantity, 1);
assert.deepEqual(validateCheckoutCart([item]), []);
assert.ok(validateCheckoutCart([{ ...item, quantity: 2 }]).some(error => error.includes('once per order')));
const eligible = count => Array.from({ length: count }, (_, index) => ({ ...item, id: `p-${index}`, product_id: `p-${index}` }));
assert.equal(calculateMockupPromotion(eligible(1)).total, 0.99);
assert.equal(calculateMockupPromotion(eligible(2)).total, 1.98);
assert.equal(calculateMockupPromotion(eligible(3)).total, 2);
assert.equal(calculateMockupPromotion(eligible(4)).total, 2.99);
assert.equal(calculateMockupPromotion(eligible(5)).total, 3.98);
assert.equal(calculateMockupPromotion(eligible(6)).total, 4);
assert.equal(calculateMockupPromotion([...eligible(3), { ...item, id: 'fb', product_id: 'fb', price: 1.2 }]).total, 3.2);
assert.equal(calculateMockupPromotion([{ ...item, price: 0.99, product_type: 'physical' }, ...eligible(2)]).discountCents, 0);

assert.match(migration, /digital-mockup-originals'[\s\S]*?false,/);
assert.match(migration, /original_sha256 text not null unique/);
assert.match(migration, /unique \(order_id, product_id, version_id\)/);
const publicView = migration.slice(migration.indexOf('create or replace view public.storefront_digital_mockups'), migration.indexOf('revoke all on public.storefront_digital_mockups'));
assert.doesNotMatch(publicView, /original_storage_path|original_sha256/);
assert.match(edge, /createSignedUrl\(\s*version\.original_storage_path,\s*expiresIn/);
assert.match(edge, /customerDownloadFileName\(product\.name, version\.original_file_name, version\.file_extension\)/);
assert.match(edge, /normalize\('NFC'\)/);
assert.match(edge, /action === 'download_file'/);
assert.match(edge, /filename\*=UTF-8''/);
assert.match(downloadsPanel, /downloadDigitalMockup/);
assert.doesNotMatch(edge, /createSignedUrl\(version\.original_storage_path, expiresIn, \{ download: version\.original_file_name \}\)/);
assert.match(edge, /const expiresIn = 120/);
assert.match(edge, /session\.payment_status !== 'paid'/);
assert.match(edge, /confirmation_email_status === 'accepted'/);
assert.match(edge, /action === 'admin_create_test_checkout'/);
assert.match(edge, /getStripeCredentials\('test'\)/);
assert.match(edge, /archive_confirmed_test_order/);
assert.match(edge, /action === 'admin_test_readiness'/);
assert.match(serviceMigration, /grant select, insert, update, delete on table[\s\S]*digital_mockup_assets/);
assert.match(testIsolationMigration, /v_is_sample boolean/);
assert.match(testIsolationMigration, /v_is_sample and v_mode <> 'test'/);
assert.match(testIsolationMigration, /record_environment/);
assert.match(webhook, /hc_apparel_digital_mockups/);
assert.match(webhook, /hc_apparel_mixed_storefront/);
assert.match(checkoutPricing, /product\.product_type === 'digital'/);
assert.match(mixedMigration, /where item ->> 'product_type' = 'physical'/);
assert.match(mixedMigration, /Digital mockups can be purchased once per order/);
assert.match(cart, /product_type === 'digital' \? 1/);
assert.match(client, /product_type: 'digital'/);
assert.match(client, /HC_LOGO_URL/);
assert.match(client, /createPublicHero/);
assert.doesNotMatch(client, /positions = \[/);
assert.doesNotMatch(client, /fillRect/);
assert.match(cleanPreviewMigration, /digital_mockup_replace_preview/);
assert.match(viewPricingMigration, /view_type in \('single_view', 'front_back'\)/);
assert.match(viewPricingMigration, /single_view_price numeric\(10,2\) not null default 0\.99/);
assert.match(viewPricingMigration, /front_back_price numeric\(10,2\) not null default 1\.20/);
assert.match(viewPricingMigration, /price_override is null or price_override > 0/);
assert.match(viewPricingMigration, /asset\.view_type/);
assert.doesNotMatch(viewPricingMigration.slice(viewPricingMigration.indexOf('create or replace view public.storefront_digital_mockups')), /original_storage_path|original_sha256/);
assert.match(youthBatchMigration, /found_count <> 5/);
assert.match(youthBatchMigration, /garment_type = 'youth'/);
assert.match(youthBatchMigration, /view_type = 'front_back'/);
assert.match(youthBatchMigration, /settings\.front_back_price/);
assert.match(presentationMigration, /presentation_type in \('studio', 'flat_lay', 'lifestyle'\)/);
assert.match(edge, /const MOCKUP_DEAL_NAME = '3 for \$2 Mockup Deal'/);
assert.match(edge, /\[32, 32, 33\]/);
assert.match(edge, /stripeMockupLines\(pricing/);
assert.match(checkoutPricing, /mockupPromotion\(items, byId\)/);
assert.match(edge, /action === 'admin_replace_derivatives'/);
assert.match(edge, /action === 'admin_original_source'/);
assert.match(storefront, /hero\?\.hero_image_url/);
assert.match(storefront, /bg-gradient-to-t/);
assert.match(storefront, /aria-label="View type"/);
assert.match(storefront, /Front \+ Back/);
assert.match(storefront, /object-contain/);
assert.match(edge, /configuredPrice\(priceSettings/);
assert.match(edge, /price_mismatch/);
assert.match(routes, /path="\/DigitalMockups"/);
assert.match(routes, /path="\/MyDownloads"/);

console.log('Digital Mockups catalog, checkout, entitlement, and mixed-cart safety checks passed.');
