-- Flexible HC Apparel package data and effective-dated Georgia destination sales tax.

alter table public.checkout_financial_settings
  add column if not exists georgia_sales_tax_enabled boolean not null default true,
  add column if not exists georgia_tax_method text not null default 'destination_based';

alter table public.checkout_financial_settings
  drop constraint if exists checkout_financial_settings_georgia_tax_method_check;
alter table public.checkout_financial_settings
  add constraint checkout_financial_settings_georgia_tax_method_check
  check (georgia_tax_method in ('destination_based'));

update public.checkout_financial_settings
set georgia_sales_tax_enabled = true,
    georgia_tax_method = 'destination_based',
    sales_tax_enabled = false,
    sales_tax_rate_percent = 0
where id = 'default';

create table if not exists public.georgia_sales_tax_rates (
  id bigint generated by default as identity primary key,
  jurisdiction_code text not null,
  jurisdiction_name text not null,
  rate_percent numeric(6,3) not null check (rate_percent >= 0 and rate_percent <= 100),
  effective_from date not null,
  effective_to date not null,
  rate_source text not null,
  source_url text not null,
  source_updated_at date not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint georgia_sales_tax_rates_period_check check (effective_to >= effective_from),
  unique (jurisdiction_code, effective_from, effective_to)
);

create table if not exists public.georgia_tax_destination_rules (
  id bigint generated by default as identity primary key,
  postal_code text not null check (postal_code ~ '^[0-9]{5}$'),
  city_normalized text not null,
  jurisdiction_code text not null,
  jurisdiction_name text not null,
  active boolean not null default true,
  priority integer not null default 100,
  rule_source text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (postal_code, city_normalized, jurisdiction_code)
);

alter table public.georgia_sales_tax_rates enable row level security;
alter table public.georgia_tax_destination_rules enable row level security;
revoke all on table public.georgia_sales_tax_rates from anon, authenticated;
revoke all on table public.georgia_tax_destination_rules from anon, authenticated;

alter table public.orders
  add column if not exists sales_tax_rate_percent numeric(6,3),
  add column if not exists sales_tax_jurisdiction_code text,
  add column if not exists sales_tax_jurisdiction_name text,
  add column if not exists sales_tax_rate_source text,
  add column if not exists sales_tax_effective_from date,
  add column if not exists sales_tax_effective_to date;

-- Current and next-quarter records needed by the validated destination rules below.
-- The table is deliberately effective-dated so quarterly updates require data changes,
-- not an application deployment.
insert into public.georgia_sales_tax_rates
  (jurisdiction_code, jurisdiction_name, rate_percent, effective_from, effective_to, rate_source, source_url, source_updated_at)
values
  ('060A', 'Atlanta (Fulton County)', 8.900, '2026-07-01', '2026-09-30', 'Georgia Department of Revenue General Rate Chart', 'https://dor.georgia.gov/document/document/general-rate-chart-effective-july-1-2026-through-september-30-2026pdf/download', '2026-07-01'),
  ('025', 'Chatham County', 7.000, '2026-07-01', '2026-09-30', 'Georgia Department of Revenue General Rate Chart', 'https://dor.georgia.gov/document/document/general-rate-chart-effective-july-1-2026-through-september-30-2026pdf/download', '2026-07-01'),
  ('033', 'Cobb County', 6.000, '2026-07-01', '2026-09-30', 'Georgia Department of Revenue General Rate Chart', 'https://dor.georgia.gov/document/document/general-rate-chart-effective-july-1-2026-through-september-30-2026pdf/download', '2026-07-01'),
  ('060A', 'Atlanta (Fulton County)', 8.900, '2026-10-01', '2026-12-31', 'Georgia Department of Revenue General Rate Chart', 'https://dor.georgia.gov/document/document/httpsdorgeorgiagovdocumentdocumentgeneral-rate-chart-effective-october-1-2026/download', '2026-09-25'),
  ('025', 'Chatham County', 7.000, '2026-10-01', '2026-12-31', 'Georgia Department of Revenue General Rate Chart', 'https://dor.georgia.gov/document/document/httpsdorgeorgiagovdocumentdocumentgeneral-rate-chart-effective-october-1-2026/download', '2026-09-25'),
  ('033', 'Cobb County', 6.000, '2026-10-01', '2026-12-31', 'Georgia Department of Revenue General Rate Chart', 'https://dor.georgia.gov/document/document/httpsdorgeorgiagovdocumentdocumentgeneral-rate-chart-effective-october-1-2026/download', '2026-09-25')
on conflict (jurisdiction_code, effective_from, effective_to) do update set
  jurisdiction_name = excluded.jurisdiction_name,
  rate_percent = excluded.rate_percent,
  rate_source = excluded.rate_source,
  source_url = excluded.source_url,
  source_updated_at = excluded.source_updated_at,
  updated_at = now();

-- Only explicit address rules are used. Unknown or ambiguous Georgia destinations
-- are blocked for review rather than assigned a guessed county.
insert into public.georgia_tax_destination_rules
  (postal_code, city_normalized, jurisdiction_code, jurisdiction_name, rule_source)
values
  ('30303', 'ATLANTA', '060A', 'Atlanta (Fulton County)', 'Validated city and ZIP destination rule'),
  ('31401', 'SAVANNAH', '025', 'Chatham County', 'Validated city and ZIP destination rule'),
  ('30060', 'MARIETTA', '033', 'Cobb County', 'Validated city and ZIP destination rule')
on conflict (postal_code, city_normalized, jurisdiction_code) do update set
  jurisdiction_name = excluded.jurisdiction_name,
  rule_source = excluded.rule_source,
  active = true,
  updated_at = now();

create or replace function public.get_georgia_checkout_tax_rate(
  destination_zip text,
  destination_city text,
  calculation_date date default current_date
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  matched_rule public.georgia_tax_destination_rules%rowtype;
  matched_rate public.georgia_sales_tax_rates%rowtype;
begin
  select * into matched_rule
  from public.georgia_tax_destination_rules
  where active = true
    and postal_code = left(regexp_replace(coalesce(destination_zip, ''), '[^0-9]', '', 'g'), 5)
    and city_normalized = upper(trim(coalesce(destination_city, '')))
  order by priority asc, id asc
  limit 1;

  if matched_rule.id is null then
    return jsonb_build_object(
      'ok', false,
      'code', 'GA_TAX_JURISDICTION_UNRESOLVED',
      'message', 'Georgia destination county or Atlanta jurisdiction could not be resolved from the delivery address.'
    );
  end if;

  select * into matched_rate
  from public.georgia_sales_tax_rates
  where jurisdiction_code = matched_rule.jurisdiction_code
    and calculation_date between effective_from and effective_to
  order by effective_from desc
  limit 1;

  if matched_rate.id is null then
    return jsonb_build_object(
      'ok', false,
      'code', 'GA_TAX_RATE_EXPIRED',
      'message', 'No effective Georgia sales-tax rate is configured for this destination and date.',
      'jurisdiction_code', matched_rule.jurisdiction_code,
      'jurisdiction_name', matched_rule.jurisdiction_name
    );
  end if;

  return jsonb_build_object(
    'ok', true,
    'method', 'destination_based',
    'jurisdiction_code', matched_rate.jurisdiction_code,
    'jurisdiction_name', matched_rate.jurisdiction_name,
    'rate_percent', matched_rate.rate_percent,
    'effective_from', matched_rate.effective_from,
    'effective_to', matched_rate.effective_to,
    'rate_source', matched_rate.rate_source,
    'source_url', matched_rate.source_url,
    'last_tax_rate_update', matched_rate.source_updated_at
  );
end;
$$;

revoke all on function public.get_georgia_checkout_tax_rate(text, text, date) from public, anon, authenticated;
grant execute on function public.get_georgia_checkout_tax_rate(text, text, date) to service_role;

create or replace function public.get_checkout_pricing_settings_server()
returns jsonb
language sql
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'id', s.id,
    'minimum_margin_per_item', s.minimum_margin_per_item,
    'processing_percent', s.processing_percent,
    'processing_fixed_fee', s.processing_fixed_fee,
    'processing_enabled', s.processing_enabled,
    'payment_method_costs', s.payment_method_costs,
    'sales_tax_enabled', s.sales_tax_enabled,
    'sales_tax_rate_percent', s.sales_tax_rate_percent,
    'georgia_sales_tax_enabled', s.georgia_sales_tax_enabled,
    'georgia_tax_method', s.georgia_tax_method,
    'ss_shipping_enabled', s.ss_shipping_enabled,
    'ss_free_freight_threshold', s.ss_free_freight_threshold,
    'ss_tier_1_2', s.ss_tier_1_2,
    'ss_tier_3_5', s.ss_tier_3_5,
    'ss_tier_6_12', s.ss_tier_6_12,
    'ss_tier_13_plus', s.ss_tier_13_plus,
    'ss_shipping_buffer', s.ss_shipping_buffer,
    'usps_enabled', s.usps_enabled,
    'usps_ground_advantage_enabled', s.usps_ground_advantage_enabled,
    'usps_priority_mail_enabled', s.usps_priority_mail_enabled,
    'origin_street', s.origin_street,
    'origin_city', s.origin_city,
    'origin_state', s.origin_state,
    'origin_zip', s.origin_zip,
    'default_product_weight_oz', s.default_product_weight_oz,
    'default_product_weight_unit', s.default_product_weight_unit,
    'default_package_length_in', s.default_package_length_in,
    'default_package_width_in', s.default_package_width_in,
    'default_package_height_in', s.default_package_height_in,
    'default_package_dimension_unit', s.default_package_dimension_unit,
    'package_presets', s.package_presets,
    'hc_fallback_enabled', s.hc_fallback_enabled,
    'hc_fallback_rate', s.hc_fallback_rate,
    'hc_free_shipping_enabled', s.hc_free_shipping_enabled,
    'hc_free_shipping_threshold', s.hc_free_shipping_threshold,
    'hc_handling_amount', s.hc_handling_amount,
    'public_visitor_price_markup_enabled', s.public_visitor_price_markup_enabled,
    'public_visitor_price_difference', s.public_visitor_price_difference
  )
  from public.checkout_financial_settings s
  where s.id = 'default'
  limit 1;
$$;

revoke all on function public.get_checkout_pricing_settings_server() from public, anon, authenticated;
grant execute on function public.get_checkout_pricing_settings_server() to service_role;

comment on table public.georgia_sales_tax_rates is
  'Server-side, effective-dated Georgia destination sales-tax rates maintained from Georgia DOR quarterly charts.';
comment on table public.georgia_tax_destination_rules is
  'Explicit Georgia delivery address-to-jurisdiction rules; unresolved destinations fail safely instead of being guessed.';
